import VisualProof.Rule.Completeness.Comprehension.Normalization.Arguments

namespace VisualProof.Rule.Completeness.Comprehension

open Diagram
open Theory
open WirePrimitive

noncomputable def argumentNormalizationPresentationAt
    {recordedArguments external firstArguments secondArguments outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (firstValues : Vars external firstArguments)
    (secondValues : Vars external secondArguments)
    (argumentsEq : firstArguments = secondArguments)
    (valuesEq : HEq firstValues secondValues) :
    RegionIso (WireEquiv.refl outer)
      (.mk (localBefore ++ .rel firstArguments :: localAfter)
        (argumentItemsEdit recordedSites firstValues
          (normalizationOperation firstArguments)
          ({ sourceKeep := Transform.Frame.keep outer localBefore
              [.rel firstArguments] localAfter
             targetKeep := Transform.Frame.keep outer localBefore
              [.rel firstArguments] localAfter
             selected := Transform.Frame.insertedHead outer localBefore localAfter
              (.rel firstArguments) } : Transform.Frame firstArguments
            (outer ++ (localBefore ++ localAfter))
            (outer ++ (localBefore ++ .rel firstArguments :: localAfter))
            (outer ++ (localBefore ++ .rel firstArguments :: localAfter)))
          PUnit.unit (fun _ _ _ => PUnit.unit)).1)
      (.mk (localBefore ++ .rel secondArguments :: localAfter)
        (argumentItemsEdit recordedSites secondValues
          (normalizationOperation secondArguments)
          ({ sourceKeep := Transform.Frame.keep outer localBefore
              [.rel secondArguments] localAfter
             targetKeep := Transform.Frame.keep outer localBefore
              [.rel secondArguments] localAfter
             selected := Transform.Frame.insertedHead outer localBefore localAfter
              (.rel secondArguments) } : Transform.Frame secondArguments
            (outer ++ (localBefore ++ localAfter))
            (outer ++ (localBefore ++ .rel secondArguments :: localAfter))
            (outer ++ (localBefore ++ .rel secondArguments :: localAfter)))
          PUnit.unit (fun _ _ _ => PUnit.unit)).1) := by
  subst secondArguments
  cases valuesEq
  exact RegionIso.refl _

/-- The authoritative all-sites region generated by a normalized argument
tuple. Every argument stage consumes this exact representation. -/
def argumentNormalizedRegionAt
    {recordedArguments external arguments outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (values : Vars external arguments) : Region outer :=
  .mk (localBefore ++ .rel arguments :: localAfter)
    (argumentItemsEdit recordedSites values
      (normalizationOperation arguments)
      ({ sourceKeep := Transform.Frame.keep outer localBefore [.rel arguments] localAfter
         targetKeep := Transform.Frame.keep outer localBefore [.rel arguments] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
           (.rel arguments) } : Transform.Frame arguments (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel arguments :: localAfter))
        (outer ++ (localBefore ++ .rel arguments :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)).1

/-- One normalized Projection CPS phase. The only mismatch is the dependent
`arguments ++ [] = arguments` presentation, discharged once here. -/
theorem argumentProjectionNormalizedAt
    {recordedArguments external arguments outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (current : Vars external arguments) (inserted : Var external signature)
    {instantiated pending : Region outer}
    (request : Telescope.Request instantiated pending)
    (pendingIso : RegionIso (WireEquiv.refl outer) pending
      (argumentNormalizedRegionAt recordedSites
        (Theory.Vars.extend current (.cons inserted .nil))))
    (prepare : request.Preparation
      (argumentNormalizedRegionAt recordedSites current)) :
    request.Result := by
  let next := Theory.Vars.extend current (.cons inserted .nil)
  have droppedEq : HEq
      (Argument.Projection.Vars.dropAt arguments next) current :=
    Argument.Projection.Vars.dropAt_extend_singleton current inserted
  let presentation := argumentNormalizationPresentationAt recordedSites current
    (Argument.Projection.Vars.dropAt arguments next)
    (List.append_nil arguments).symm droppedEq.symm
  let rawPending : Region outer :=
    .mk (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter)
      (argumentItemsEdit recordedSites next
        (Argument.Projection.operation arguments [] signature)
        (Argument.Projection.rootFrame outer localBefore localAfter arguments []
          signature)
        (Argument.Projection.targetHead outer localBefore localAfter arguments [])
        (fun _ _ _ => PUnit.unit)).1
  have pendingEq : argumentNormalizedRegionAt recordedSites next = rawPending := by
    dsimp only [argumentNormalizedRegionAt, rawPending]
    apply congrArg (Region.mk (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites next
      (normalizationOperation (arguments ++ signature :: []))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (arguments ++ signature :: [])] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (arguments ++ signature :: [])] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (arguments ++ signature :: [])) } : Transform.Frame
        (arguments ++ signature :: []) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter))
        (outer ++ (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)
      (Argument.Projection.operation arguments [] signature)
      (Argument.Projection.rootFrame outer localBefore localAfter arguments [] signature)
      (Argument.Projection.targetHead outer localBefore localAfter arguments [])
      (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [Argument.Projection.rootFrame, Transform.Frame.replace]) (by
          simp [Argument.Projection.rootFrame, Transform.Frame.replace])
  have stagedPrepare : request.Preparation
      (.mk (localBefore ++ .rel (arguments ++ []) :: localAfter)
        (argumentItemsEdit recordedSites
          (Argument.Projection.Vars.dropAt arguments next)
          (normalizationOperation (arguments ++ []))
          ({ sourceKeep :=
              (Argument.Projection.rootFrame outer localBefore localAfter arguments []
                signature).targetKeep
             targetKeep :=
              (Argument.Projection.rootFrame outer localBefore localAfter arguments []
                signature).targetKeep
             selected := Argument.Projection.targetHead outer localBefore localAfter
               arguments [] } : Transform.Frame (arguments ++ [])
            (outer ++ (localBefore ++ localAfter))
            (outer ++ (localBefore ++ .rel (arguments ++ []) :: localAfter))
            (outer ++ (localBefore ++ .rel (arguments ++ []) :: localAfter)))
          PUnit.unit (fun _ _ _ => PUnit.unit)).1) := by
    simpa only [argumentNormalizedRegionAt, Argument.Projection.rootFrame,
      Transform.Frame.replace] using prepare.rawIso presentation
  exact argumentProjectionStage (before := arguments) (after := [])
    (outer := outer) (localBefore := localBefore) (localAfter := localAfter)
      (instantiated := instantiated) recordedSites next
      (request := request) (pendingIso.trans (RegionIso.ofEq pendingEq))
      stagedPrepare

/-- Prepending one recorded argument preserves occurrence validity because it
is exactly Projection's extension direction. -/
theorem argumentPrependValidityAt
    {recordedArguments external arguments outer localBefore localAfter boundary
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (inserted : Var external signature) (current : Vars external arguments)
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    (currentCanonical : (context.fill
      (argumentNormalizedRegionAt recordedSites current)).Canonical)
    (currentExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill
        (argumentNormalizedRegionAt recordedSites current))) :
    (context.fill (argumentNormalizedRegionAt recordedSites
      (.cons inserted current))).Canonical ∧
      OpenDiagram.ExternalTwoEnded interface.boundaryWire
        (context.fill (argumentNormalizedRegionAt recordedSites
          (.cons inserted current))) := by
  let next : Vars external ([] ++ signature :: arguments) :=
    .cons inserted current
  let generated := argumentItemsEdit recordedSites next
    (Argument.Projection.operation [] arguments signature)
    (Argument.Projection.rootFrame outer localBefore localAfter [] arguments signature)
    (Argument.Projection.targetHead outer localBefore localAfter [] arguments)
    (fun _ _ _ => PUnit.unit)
  let description : Argument.Projection.Drops.Description outer := {
    before := []
    after := arguments
    localBefore := localBefore
    localAfter := localAfter
    signature := signature
    items := generated.1
    itemsEdit := generated.2
  }
  have sourceEq : argumentNormalizedRegionAt recordedSites
      (.cons inserted current) = description.source := by
    dsimp only [argumentNormalizedRegionAt, description, generated, next]
    apply congrArg (Region.mk (localBefore ++ .rel (signature :: arguments) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites
      (.cons inserted current) (normalizationOperation (signature :: arguments))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (signature :: arguments)] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (signature :: arguments)] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (signature :: arguments)) } : Transform.Frame
        (signature :: arguments) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (signature :: arguments) :: localAfter))
        (outer ++ (localBefore ++ .rel (signature :: arguments) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)
      (Argument.Projection.operation [] arguments signature)
      (Argument.Projection.rootFrame outer localBefore localAfter [] arguments signature)
      (Argument.Projection.targetHead outer localBefore localAfter [] arguments)
      (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [Argument.Projection.rootFrame, Transform.Frame.replace]) (by
          simp [Argument.Projection.rootFrame, Transform.Frame.replace])
  let targetIso : RegionIso (WireEquiv.refl outer) description.target
      (argumentNormalizedRegionAt recordedSites current) := by
    simpa only [description, generated, next, argumentNormalizedRegionAt] using
      argumentProjectionEndpointIso (outer := outer) (localBefore := localBefore)
        (localAfter := localAfter) (before := []) (after := arguments)
        recordedSites next
  let filledTargetIso := DiagramContext.fillIso context targetIso
  have filledTargetCanonical : (context.fill description.target).Canonical :=
    filledTargetIso.canonical_iff.mpr currentCanonical
  have filledTargetExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill description.target) := by
    let currentEndpoint := interface.withBody
      (context.fill (argumentNormalizedRegionAt recordedSites current))
      currentCanonical currentExternalTwoEnded
    apply currentEndpoint.externalTwoEnded_of_nonempty_iff
    intro wireSignature wire
    have lengthEq := filledTargetIso.incidencePaths_length_eq wire
    constructor <;> intro nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq.symm ▸ nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq ▸ nonempty
  have localTargetCanonical : description.target.Canonical :=
    context.holeCanonical description.target filledTargetCanonical
  have localExtension := description.target_source_extension localTargetCanonical
  have filledExtension := context.extendCanonical description.target
    description.source filledTargetCanonical localExtension.1 localExtension.2
  have filledSourceExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill description.source) := by
    intro wireSignature wire
    exact Nat.le_trans (filledTargetExternalTwoEnded wire)
      (Nat.add_le_add_left (filledExtension.2 wire).length_le _)
  rw [sourceEq]
  exact ⟨filledExtension.1, filledSourceExternalTwoEnded⟩

/-- Adding a whole tuple in front of the canonical external tuple preserves
validity, by repeated Projection extension. -/
theorem argumentExtendedValidityAt
    {recordedArguments external arguments outer localBefore localAfter boundary
      recordedSourceWires recordedTargetWires : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (added : Vars external arguments)
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    (finalCanonical : (context.fill
      (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))).Canonical)
    (finalExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill
        (argumentNormalizedRegionAt recordedSites
          (EqualityNormalization.formalPorts external)))) :
    (context.fill (argumentNormalizedRegionAt recordedSites
      (Theory.Vars.extend added
        (EqualityNormalization.formalPorts external)))).Canonical ∧
      OpenDiagram.ExternalTwoEnded interface.boundaryWire
        (context.fill (argumentNormalizedRegionAt recordedSites
          (Theory.Vars.extend added
            (EqualityNormalization.formalPorts external)))) := by
  induction added with
  | nil => exact ⟨finalCanonical, finalExternalTwoEnded⟩
  | @cons signature rest head tail induction =>
      exact argumentPrependValidityAt recordedSites head
        (Theory.Vars.extend tail
          (EqualityNormalization.formalPorts external)) interface context
        induction.1 induction.2

/-- Move the current tuple head behind `before`, preserving the authoritative
normalized representation on both sides of the permutation step. -/
theorem argumentPermutationNormalizedAt
    {recordedArguments external before after outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (current : Vars external (signature :: before ++ after))
    {instantiated : Region outer}
    (request : Telescope.Request instantiated
      (argumentNormalizedRegionAt recordedSites
        ((ArgumentPermutation.Permutation.moveHead signature before after).mapVars
          current)))
    (prepare : request.Preparation
      (argumentNormalizedRegionAt recordedSites current)) :
    request.Result := by
  let moved :=
    (ArgumentPermutation.Permutation.moveHead signature before after).mapVars
      current
  let rawPrepared : Region outer :=
    .mk (localBefore ++ .rel (signature :: before ++ after) :: localAfter)
      (argumentItemsEdit recordedSites current
        (ArgumentPermutation.operation (signature :: before ++ after)
          (before ++ signature :: after)
          (ArgumentPermutation.Permutation.moveHead signature before after))
        (ArgumentPermutation.rootFrame outer localBefore localAfter
          (signature :: before ++ after) (before ++ signature :: after))
        (ArgumentPermutation.targetHead outer localBefore localAfter
          (before ++ signature :: after))
        (fun _ _ _ => PUnit.unit)).1
  have preparedEq : argumentNormalizedRegionAt recordedSites current =
      rawPrepared := by
    dsimp only [argumentNormalizedRegionAt, rawPrepared]
    apply congrArg (Region.mk (localBefore ++ .rel (signature :: before ++ after) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites current
      (normalizationOperation (signature :: before ++ after))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (signature :: before ++ after)] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (signature :: before ++ after)] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (signature :: before ++ after)) } : Transform.Frame
        (signature :: before ++ after) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (signature :: before ++ after) :: localAfter))
        (outer ++ (localBefore ++ .rel (signature :: before ++ after) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)
      (ArgumentPermutation.operation (signature :: before ++ after)
        (before ++ signature :: after)
        (ArgumentPermutation.Permutation.moveHead signature before after))
      (ArgumentPermutation.rootFrame outer localBefore localAfter
        (signature :: before ++ after) (before ++ signature :: after))
      (ArgumentPermutation.targetHead outer localBefore localAfter
        (before ++ signature :: after))
      (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [ArgumentPermutation.rootFrame, Transform.Frame.replace]) (by
          simp [ArgumentPermutation.rootFrame, Transform.Frame.replace])
  have pendingEq : argumentNormalizedRegionAt recordedSites moved =
      (.mk (localBefore ++ .rel (before ++ signature :: after) :: localAfter)
        (argumentItemsEdit recordedSites moved
          (normalizationOperation (before ++ signature :: after))
          ({ sourceKeep :=
              (ArgumentPermutation.rootFrame outer localBefore localAfter
                (signature :: before ++ after)
                (before ++ signature :: after)).targetKeep
             targetKeep :=
              (ArgumentPermutation.rootFrame outer localBefore localAfter
                (signature :: before ++ after)
                (before ++ signature :: after)).targetKeep
             selected := ArgumentPermutation.targetHead outer localBefore localAfter
               (before ++ signature :: after) } : Transform.Frame
            (before ++ signature :: after) (outer ++ (localBefore ++ localAfter))
            (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter))
            (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter)))
          PUnit.unit (fun _ _ _ => PUnit.unit)).1) := by
    rfl
  exact argumentPermutationStage (outer := outer) (localBefore := localBefore)
    (localAfter := localAfter) (instantiated := instantiated) recordedSites current
    (request := request) (RegionIso.ofEq pendingEq)
    (prepare.rawIso (RegionIso.ofEq preparedEq))

/-- Contract one adjacent duplicated argument while preserving normalized
all-sites regions as the authoritative continuation endpoints. -/
theorem argumentDuplicateNormalizedAt
    {recordedArguments external before after outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (next : Vars external (before ++ signature :: after))
    {instantiated pending : Region outer}
    (request : Telescope.Request instantiated pending)
    (pendingIso : RegionIso (WireEquiv.refl outer) pending
      (argumentNormalizedRegionAt recordedSites next))
    (prepare : request.Preparation
      (argumentNormalizedRegionAt recordedSites
        (Argument.Duplicate.Vars.duplicateAt before next))) :
    request.Result := by
  let duplicated := Argument.Duplicate.Vars.duplicateAt before next
  let rawPending : Region outer :=
    .mk (localBefore ++ .rel (before ++ signature :: after) :: localAfter)
      (argumentItemsEdit recordedSites next
        (Argument.Duplicate.operation before after signature)
        (Argument.Duplicate.rootFrame outer localBefore localAfter before after signature)
        (Argument.Duplicate.targetHead outer localBefore localAfter before after signature)
        (fun _ _ _ => PUnit.unit)).1
  have pendingEq : argumentNormalizedRegionAt recordedSites next = rawPending := by
    dsimp only [argumentNormalizedRegionAt, rawPending]
    apply congrArg (Region.mk (localBefore ++ .rel (before ++ signature :: after) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites next
      (normalizationOperation (before ++ signature :: after))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (before ++ signature :: after)] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (before ++ signature :: after)] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (before ++ signature :: after)) } : Transform.Frame
        (before ++ signature :: after) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter))
        (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)
      (Argument.Duplicate.operation before after signature)
      (Argument.Duplicate.rootFrame outer localBefore localAfter before after signature)
      (Argument.Duplicate.targetHead outer localBefore localAfter before after signature)
      (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [Argument.Duplicate.rootFrame, Transform.Frame.replace]) (by
          simp [Argument.Duplicate.rootFrame, Transform.Frame.replace])
  have preparedEq : argumentNormalizedRegionAt recordedSites duplicated =
      (.mk (localBefore ++ .rel (before ++ signature :: signature :: after) :: localAfter)
        (argumentItemsEdit recordedSites duplicated
          (normalizationOperation (before ++ signature :: signature :: after))
          ({ sourceKeep :=
              (Argument.Duplicate.rootFrame outer localBefore localAfter before after
                signature).targetKeep
             targetKeep :=
              (Argument.Duplicate.rootFrame outer localBefore localAfter before after
                signature).targetKeep
             selected := Argument.Duplicate.targetHead outer localBefore localAfter
               before after signature } : Transform.Frame
            (before ++ signature :: signature :: after)
            (outer ++ (localBefore ++ localAfter))
            (outer ++ (localBefore ++
              .rel (before ++ signature :: signature :: after) :: localAfter))
            (outer ++ (localBefore ++
              .rel (before ++ signature :: signature :: after) :: localAfter)))
          PUnit.unit (fun _ _ _ => PUnit.unit)).1) := by
    rfl
  exact argumentDuplicateContractStage (outer := outer) (localBefore := localBefore)
    (localAfter := localAfter) (instantiated := instantiated) recordedSites next
    (request := request) (pendingIso.trans (RegionIso.ofEq pendingEq))
    (prepare.rawIso (RegionIso.ofEq preparedEq))

/-- One argument occurrence is moved next to its canonical external copy and
contracted.  Both primitives are packaged here so the intrinsic-position
eliminator has no caller-visible intermediate endpoint. -/
theorem argumentMoveDuplicateNormalizedAt
    {recordedArguments external before after outer localBefore localAfter
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (current : Vars external
      (signature :: before ++ signature :: after))
    (next : Vars external (before ++ signature :: after))
    (movedEq :
      (ArgumentPermutation.Permutation.moveHead signature before
        (signature :: after)).mapVars
          current =
        Argument.Duplicate.Vars.duplicateAt before next)
    {instantiated pending : Region outer}
    (request : Telescope.Request instantiated pending)
    (pendingIso : RegionIso (WireEquiv.refl outer) pending
      (argumentNormalizedRegionAt recordedSites next))
    (prepare : request.Preparation
      (argumentNormalizedRegionAt recordedSites current)) :
    request.Result := by
  let duplicated := Argument.Duplicate.Vars.duplicateAt before next
  let moved :=
    (ArgumentPermutation.Permutation.moveHead signature before
      (signature :: after)).mapVars
      current
  have movedRegionEq : argumentNormalizedRegionAt recordedSites moved =
      argumentNormalizedRegionAt recordedSites duplicated := by
    exact congrArg (argumentNormalizedRegionAt recordedSites) movedEq
  let generated := argumentItemsEdit recordedSites next
    (Argument.Duplicate.operation before after signature)
    (Argument.Duplicate.rootFrame outer localBefore localAfter before after signature)
    (Argument.Duplicate.targetHead outer localBefore localAfter before after signature)
    (fun _ _ _ => PUnit.unit)
  let description : Argument.Duplicate.Duplicates.Description outer := {
    before := before
    after := after
    localBefore := localBefore
    localAfter := localAfter
    signature := signature
    items := generated.1
    itemsEdit := generated.2
  }
  have sourceEq : description.source =
      argumentNormalizedRegionAt recordedSites next := by
    dsimp only [description, generated, argumentNormalizedRegionAt]
    apply congrArg (Region.mk (localBefore ++ .rel (before ++ signature :: after) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites next
      (Argument.Duplicate.operation before after signature)
      (Argument.Duplicate.rootFrame outer localBefore localAfter before after signature)
      (Argument.Duplicate.targetHead outer localBefore localAfter before after signature)
      (fun _ _ _ => PUnit.unit)
      (normalizationOperation (before ++ signature :: after))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (before ++ signature :: after)] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (before ++ signature :: after)] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (before ++ signature :: after)) } : Transform.Frame
        (before ++ signature :: after) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter))
        (outer ++ (localBefore ++ .rel (before ++ signature :: after) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [Argument.Duplicate.rootFrame, Transform.Frame.replace]) (by
          simp [Argument.Duplicate.rootFrame, Transform.Frame.replace])
  let sourceIso : RegionIso (WireEquiv.refl outer) description.source
      (argumentNormalizedRegionAt recordedSites next) := RegionIso.ofEq sourceEq
  let exactSourceIso := sourceIso.trans pendingIso.symm
  let filledSourceIso := DiagramContext.fillIso request.occurrence.context
    exactSourceIso
  have filledSourceCanonical :
      (request.occurrence.context.fill description.source).Canonical :=
    filledSourceIso.canonical_iff.mpr request.pendingCanonical
  have filledSourceExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      request.occurrence.interface.boundaryWire
      (request.occurrence.context.fill description.source) := by
    let pendingEndpoint := request.occurrence.interface.withBody
      (request.occurrence.context.fill pending)
      request.pendingCanonical request.pendingExternalTwoEnded
    apply pendingEndpoint.externalTwoEnded_of_nonempty_iff
    intro wireSignature wire
    have lengthEq := filledSourceIso.incidencePaths_length_eq wire
    constructor <;> intro nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq.symm ▸ nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq ▸ nonempty
  have localSourceCanonical : description.source.Canonical :=
    request.occurrence.context.holeCanonical description.source
      filledSourceCanonical
  have localExpansion := description.source_target_extension
    localSourceCanonical
  have filledExpansion := request.occurrence.context.extendCanonical
    description.source description.target filledSourceCanonical
      localExpansion.1 localExpansion.2
  have filledTargetExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      request.occurrence.interface.boundaryWire
      (request.occurrence.context.fill description.target) := by
    intro wireSignature wire
    exact Nat.le_trans (filledSourceExternalTwoEnded wire)
      (Nat.add_le_add_left (filledExpansion.2 wire).length_le _)
  have targetIso : RegionIso (WireEquiv.refl outer) description.target
      (argumentNormalizedRegionAt recordedSites duplicated) := by
    simpa only [description, generated, argumentNormalizedRegionAt] using
      argumentDuplicateEndpointIso (outer := outer) (localBefore := localBefore)
        (localAfter := localAfter) recordedSites next
  let filledTargetIso := DiagramContext.fillIso request.occurrence.context
    targetIso
  have duplicatedCanonical : (request.occurrence.context.fill
      (argumentNormalizedRegionAt recordedSites duplicated)).Canonical :=
    filledTargetIso.canonical_iff.mp filledExpansion.1
  have duplicatedExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      request.occurrence.interface.boundaryWire
      (request.occurrence.context.fill
        (argumentNormalizedRegionAt recordedSites duplicated)) := by
    let targetEndpoint := request.occurrence.interface.withBody
      (request.occurrence.context.fill description.target) filledExpansion.1
      filledTargetExternalTwoEnded
    apply targetEndpoint.externalTwoEnded_of_nonempty_iff
    intro wireSignature wire
    have lengthEq := filledTargetIso.incidencePaths_length_eq wire
    constructor <;> intro nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq ▸ nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq.symm ▸ nonempty
  have movedCanonical : (request.occurrence.context.fill
      (argumentNormalizedRegionAt recordedSites moved)).Canonical := by
    rw [movedRegionEq]
    exact duplicatedCanonical
  have movedExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      request.occurrence.interface.boundaryWire
      (request.occurrence.context.fill
        (argumentNormalizedRegionAt recordedSites moved)) := by
    rw [movedRegionEq]
    exact duplicatedExternalTwoEnded
  let stageInterface : OpenDiagram request.boundary :=
    request.occurrence.interface
  let stageContext : DiagramContext stageInterface.external outer :=
    request.occurrence.context
  have duplicateSourceCanonical :
      (stageContext.fill (polaritySource request.polarity
        (argumentNormalizedRegionAt recordedSites duplicated)
        request.endpoint)).Canonical := by
    exact match request.polarity with
      | .positive => by
          simpa only [stageContext] using duplicatedCanonical
      | .negative => by
          simpa only [stageContext] using request.endpointCanonical
  have duplicateSourceExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      stageInterface.boundaryWire
      (stageContext.fill (polaritySource request.polarity
        (argumentNormalizedRegionAt recordedSites duplicated)
        request.endpoint)) := by
    exact match request.polarity with
      | .positive => by
          simpa only [stageInterface, stageContext] using
            duplicatedExternalTwoEnded
      | .negative => by
          simpa only [stageInterface, stageContext] using
            request.endpointExternalTwoEnded
  let duplicateRequest : Telescope.Request
      (argumentNormalizedRegionAt recordedSites duplicated)
      pending := {
    boundary := request.boundary
    source := stageInterface.withBody
      (stageContext.fill (polaritySource request.polarity
        (argumentNormalizedRegionAt recordedSites duplicated) request.endpoint))
      duplicateSourceCanonical duplicateSourceExternalTwoEnded
    endpoint := request.endpoint
    polarity := request.polarity
    occurrence := exactOccurrence stageInterface
      stageContext (polaritySource request.polarity
        (argumentNormalizedRegionAt recordedSites duplicated) request.endpoint)
      duplicateSourceCanonical duplicateSourceExternalTwoEnded
    instantiatedCanonical := duplicatedCanonical
    instantiatedExternalTwoEnded := duplicatedExternalTwoEnded
    pendingCanonical := request.pendingCanonical
    pendingExternalTwoEnded := request.pendingExternalTwoEnded
    endpointCanonical := request.endpointCanonical
    endpointExternalTwoEnded := request.endpointExternalTwoEnded
    continuation := request.continuation
  }
  let duplicatePreparation : duplicateRequest.Preparation
      (argumentNormalizedRegionAt recordedSites duplicated) := {
    prepared := argumentNormalizedRegionAt recordedSites duplicated
    preparedCanonical := duplicatedCanonical
    preparedExternalTwoEnded := duplicatedExternalTwoEnded
    rawPreparedCanonical := duplicatedCanonical
    rawPreparedExternalTwoEnded := duplicatedExternalTwoEnded
    preparedIso := RegionIso.refl _
    telescope := Telescope.refl request.polarity request.occurrence.interface
      request.occurrence.context duplicatedCanonical
      duplicatedExternalTwoEnded request.continuation.1
  }
  have duplicateCompiled := argumentDuplicateNormalizedAt recordedSites next
    duplicateRequest pendingIso duplicatePreparation
  have duplicateTelescope : Telescope request.polarity
      request.occurrence.interface request.occurrence.context
      (argumentNormalizedRegionAt recordedSites moved) request.endpoint
      movedCanonical movedExternalTwoEnded request.endpointCanonical
      request.endpointExternalTwoEnded := by
    simpa only [movedRegionEq] using
      Telescope.StrictDerives.toTelescope request.polarity
      request.occurrence.interface request.occurrence.context
      duplicatedCanonical duplicatedExternalTwoEnded request.endpointCanonical
      request.endpointExternalTwoEnded request.continuation.1
      duplicateCompiled
  let permutationRequest : Telescope.Request instantiated
      (argumentNormalizedRegionAt recordedSites moved) := {
    boundary := request.boundary
    source := request.source
    endpoint := request.endpoint
    polarity := request.polarity
    occurrence := request.occurrence
    instantiatedCanonical := request.instantiatedCanonical
    instantiatedExternalTwoEnded := request.instantiatedExternalTwoEnded
    pendingCanonical := movedCanonical
    pendingExternalTwoEnded := movedExternalTwoEnded
    endpointCanonical := request.endpointCanonical
    endpointExternalTwoEnded := request.endpointExternalTwoEnded
    continuation := duplicateTelescope
  }
  let permutationPreparation : permutationRequest.Preparation
      (argumentNormalizedRegionAt recordedSites current) := {
    prepared := prepare.prepared
    preparedCanonical := prepare.preparedCanonical
    preparedExternalTwoEnded := prepare.preparedExternalTwoEnded
    rawPreparedCanonical := prepare.rawPreparedCanonical
    rawPreparedExternalTwoEnded := prepare.rawPreparedExternalTwoEnded
    preparedIso := prepare.preparedIso
    telescope := prepare.telescope
  }
  exact argumentPermutationNormalizedAt recordedSites current permutationRequest
    permutationPreparation

/-- Contract every leading actual argument against its canonical occurrence
in the external tuple.  The recursion is on the existing intrinsic `Vars`
value; each head position is eliminated in `Prop` and immediately consumed by
the combined move/duplicate phase. -/
theorem argumentVarsContractTelescopeAt
    {recordedArguments external addedArguments outer localBefore localAfter boundary
      recordedSourceWires recordedTargetWires : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (added : Vars external addedArguments)
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    {endpoint : Region outer}
    (finalCanonical : (context.fill (argumentNormalizedRegionAt recordedSites
      (EqualityNormalization.formalPorts external))).Canonical)
    (finalExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill (argumentNormalizedRegionAt
        recordedSites (EqualityNormalization.formalPorts external))))
    (endpointCanonical : (context.fill endpoint).Canonical)
    (endpointExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill endpoint))
    (polarity : Polarity) (polarityEq : context.polarity = polarity)
    (continuation : Telescope polarity interface context
      (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external)) endpoint
      finalCanonical finalExternalTwoEnded endpointCanonical
      endpointExternalTwoEnded) :
    Telescope polarity interface context
      (argumentNormalizedRegionAt recordedSites
        (Theory.Vars.extend added
          (EqualityNormalization.formalPorts external))) endpoint
      (argumentExtendedValidityAt recordedSites added interface context
        finalCanonical finalExternalTwoEnded).1
      (argumentExtendedValidityAt recordedSites added interface context
        finalCanonical finalExternalTwoEnded).2
      endpointCanonical endpointExternalTwoEnded := by
  induction added with
  | nil => exact continuation
  | @cons signature restArguments head tail induction =>
      let next := Theory.Vars.extend tail
        (EqualityNormalization.formalPorts external)
      let current := Theory.Vars.cons head next
      have nextValidity := argumentExtendedValidityAt recordedSites tail
        interface context finalCanonical finalExternalTwoEnded
      have currentValidity := argumentExtendedValidityAt recordedSites
        (.cons head tail) interface context finalCanonical
        finalExternalTwoEnded
      have tailTelescope := induction
      obtain ⟨before, after, externalEq, headEq⟩ := intrinsicVar_position head
      cases externalEq
      cases headEq
      let prefixValues : Vars (before ++ signature :: after) before :=
        (EqualityNormalization.formalPorts before).map fun wire =>
          wire.appendLeft (signature :: after)
      let suffixValues : Vars (before ++ signature :: after) after :=
        (EqualityNormalization.formalPorts after).map fun wire =>
          Var.appendRight before (.there wire)
      let selected : Var (before ++ signature :: after) signature :=
        Var.appendRight before (.here : Var (signature :: after) signature)
      have formalEq : EqualityNormalization.formalPorts
          (before ++ signature :: after) =
          Theory.Vars.extend prefixValues (.cons selected suffixValues) := by
        rw [EqualityNormalization.formalPorts_append before
          (signature :: after)]
        dsimp only [prefixValues, selected, suffixValues]
        apply congrArg (Theory.Vars.extend
          ((EqualityNormalization.formalPorts before).map fun wire =>
            wire.appendLeft (signature :: after)))
        simp only [EqualityNormalization.formalPorts,
          Erasure.Exposure.identityBoundary, Theory.Vars.map,
          Theory.Vars.extend]
        apply congrArg (Theory.Vars.cons
          (Var.appendRight before
            (.here : Var (signature :: after) signature)))
        rw [Theory.Vars.map_map]
      let stageBeforeValues := Theory.Vars.extend tail prefixValues
      let stageNext := Theory.Vars.extend stageBeforeValues
        (Theory.Vars.cons selected suffixValues)
      let stageCurrent := Theory.Vars.cons selected
        (Theory.Vars.extend stageBeforeValues
          (Theory.Vars.cons selected suffixValues))
      have nextEq : HEq stageNext next := by
        dsimp only [stageNext, stageBeforeValues, next]
        exact (Theory.Vars.extend_assoc tail prefixValues
          (Theory.Vars.cons selected suffixValues)).trans
            (heq_of_eq (congrArg (Theory.Vars.extend tail) formalEq.symm))
      have currentEq : HEq stageCurrent current := by
        dsimp only [stageCurrent, current]
        congr 1
        exact List.append_assoc _ _ _
      have movedEq :
          (ArgumentPermutation.Permutation.moveHead signature
            (restArguments ++ before) (signature :: after)).mapVars
              stageCurrent =
            Argument.Duplicate.Vars.duplicateAt
              (restArguments ++ before) stageNext := by
        dsimp only [stageCurrent, stageNext, stageBeforeValues]
        rw [ArgumentPermutation.Permutation.moveHead_cons_extend]
        rw [Argument.Duplicate.Vars.duplicateAt_extend]
      let pendingPresentation := argumentNormalizationPresentationAt
        recordedSites next stageNext
        (List.append_assoc restArguments before
          (signature :: after)).symm nextEq.symm
      let preparedPresentation := argumentNormalizationPresentationAt
        recordedSites current stageCurrent
        (congrArg (List.cons signature)
          (List.append_assoc restArguments before
            (signature :: after)).symm) currentEq.symm
      let request : Telescope.Request
          (argumentNormalizedRegionAt recordedSites current)
          (argumentNormalizedRegionAt recordedSites next) := {
        boundary := boundary
        source := interface.withBody
          (context.fill (polaritySource polarity
            (argumentNormalizedRegionAt recordedSites current) endpoint))
          (match polarity with
          | .positive => currentValidity.1
          | .negative => endpointCanonical)
          (match polarity with
          | .positive => currentValidity.2
          | .negative => endpointExternalTwoEnded)
        endpoint := endpoint
        polarity := polarity
        occurrence := exactOccurrence interface context
          (polaritySource polarity
            (argumentNormalizedRegionAt recordedSites current) endpoint)
          (match polarity with
          | .positive => currentValidity.1
          | .negative => endpointCanonical)
          (match polarity with
          | .positive => currentValidity.2
          | .negative => endpointExternalTwoEnded)
        instantiatedCanonical := currentValidity.1
        instantiatedExternalTwoEnded := currentValidity.2
        pendingCanonical := nextValidity.1
        pendingExternalTwoEnded := nextValidity.2
        endpointCanonical := endpointCanonical
        endpointExternalTwoEnded := endpointExternalTwoEnded
        continuation := tailTelescope
      }
      let prepare : request.Preparation
          (argumentNormalizedRegionAt recordedSites current) := {
        prepared := argumentNormalizedRegionAt recordedSites current
        preparedCanonical := currentValidity.1
        preparedExternalTwoEnded := currentValidity.2
        rawPreparedCanonical := currentValidity.1
        rawPreparedExternalTwoEnded := currentValidity.2
        preparedIso := RegionIso.refl _
        telescope := Telescope.refl polarity interface context
          currentValidity.1 currentValidity.2 polarityEq
      }
      have derived := argumentMoveDuplicateNormalizedAt recordedSites
        stageCurrent stageNext movedEq request pendingPresentation
        (prepare.rawIso preparedPresentation)
      exact Telescope.StrictDerives.toTelescope polarity interface context
        currentValidity.1 currentValidity.2 endpointCanonical
        endpointExternalTwoEnded polarityEq derived

/-- Appending one argument preserves occurrence validity by Projection's
extension direction. -/
theorem argumentAppendValidityAt
    {recordedArguments external arguments outer localBefore localAfter boundary
      recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (current : Vars external arguments) (inserted : Var external signature)
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    (currentCanonical : (context.fill
      (argumentNormalizedRegionAt recordedSites current)).Canonical)
    (currentExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill
        (argumentNormalizedRegionAt recordedSites current))) :
    (context.fill (argumentNormalizedRegionAt recordedSites
      (Theory.Vars.extend current
        (Theory.Vars.cons inserted Theory.Vars.nil)))).Canonical ∧
      OpenDiagram.ExternalTwoEnded interface.boundaryWire
        (context.fill (argumentNormalizedRegionAt recordedSites
          (Theory.Vars.extend current
            (Theory.Vars.cons inserted Theory.Vars.nil)))) := by
  let next := Theory.Vars.extend current
    (Theory.Vars.cons inserted Theory.Vars.nil)
  let generated := argumentItemsEdit recordedSites next
    (Argument.Projection.operation arguments [] signature)
    (Argument.Projection.rootFrame outer localBefore localAfter arguments [] signature)
    (Argument.Projection.targetHead outer localBefore localAfter arguments [])
    (fun _ _ _ => PUnit.unit)
  let description : Argument.Projection.Drops.Description outer := {
    before := arguments
    after := []
    localBefore := localBefore
    localAfter := localAfter
    signature := signature
    items := generated.1
    itemsEdit := generated.2
  }
  have sourceEq : argumentNormalizedRegionAt recordedSites next =
      description.source := by
    dsimp only [argumentNormalizedRegionAt, description, generated, next]
    apply congrArg (Region.mk (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter))
    exact argumentItemsEdit_source_independent recordedSites next
      (normalizationOperation (arguments ++ signature :: []))
      ({ sourceKeep := Transform.Frame.keep outer localBefore
          [.rel (arguments ++ signature :: [])] localAfter
         targetKeep := Transform.Frame.keep outer localBefore
          [.rel (arguments ++ signature :: [])] localAfter
         selected := Transform.Frame.insertedHead outer localBefore localAfter
          (.rel (arguments ++ signature :: [])) } : Transform.Frame
        (arguments ++ signature :: []) (outer ++ (localBefore ++ localAfter))
        (outer ++ (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter))
        (outer ++ (localBefore ++ .rel (arguments ++ signature :: []) :: localAfter)))
      PUnit.unit (fun _ _ _ => PUnit.unit)
      (Argument.Projection.operation arguments [] signature)
      (Argument.Projection.rootFrame outer localBefore localAfter arguments [] signature)
      (Argument.Projection.targetHead outer localBefore localAfter arguments [])
      (fun _ _ _ => PUnit.unit) (by
        intro wireSignature wire
        simp [Argument.Projection.rootFrame, Transform.Frame.replace]) (by
          simp [Argument.Projection.rootFrame, Transform.Frame.replace])
  let targetPresentation := argumentNormalizationPresentationAt recordedSites
    current (Argument.Projection.Vars.dropAt arguments next)
    (List.append_nil arguments).symm
    (Argument.Projection.Vars.dropAt_extend_singleton current inserted).symm
  let targetIso : RegionIso (WireEquiv.refl outer) description.target
      (argumentNormalizedRegionAt recordedSites current) := by
    simpa only [description, generated, next, argumentNormalizedRegionAt] using
      (argumentProjectionEndpointIso (outer := outer) (localBefore := localBefore)
        (localAfter := localAfter) (before := arguments) (after := [])
        recordedSites next).trans targetPresentation.symm
  let filledTargetIso := DiagramContext.fillIso context targetIso
  have targetCanonical : (context.fill description.target).Canonical :=
    filledTargetIso.canonical_iff.mpr currentCanonical
  have targetExternal : OpenDiagram.ExternalTwoEnded interface.boundaryWire
      (context.fill description.target) := by
    let endpoint := interface.withBody
      (context.fill (argumentNormalizedRegionAt recordedSites current))
      currentCanonical currentExternalTwoEnded
    apply endpoint.externalTwoEnded_of_nonempty_iff
    intro wireSignature wire
    have lengthEq := filledTargetIso.incidencePaths_length_eq wire
    constructor <;> intro nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq.symm ▸ nonempty
    · rw [← List.length_pos_iff] at nonempty ⊢
      exact lengthEq ▸ nonempty
  have localTarget := context.holeCanonical description.target targetCanonical
  have extension := description.target_source_extension localTarget
  have filled := context.extendCanonical description.target description.source
    targetCanonical extension.1 extension.2
  have sourceExternal : OpenDiagram.ExternalTwoEnded interface.boundaryWire
      (context.fill description.source) := by
    intro wireSignature wire
    exact Nat.le_trans (targetExternal wire)
      (Nat.add_le_add_left (filled.2 wire).length_le _)
  rw [sourceEq]
  exact ⟨filled.1, sourceExternal⟩

/-- Append a nonempty tuple by Projection, retaining an arbitrary presented
final endpoint.  The recursive result is used immediately as the
continuation of the head Projection, so no stage certificate escapes. -/
theorem argumentVarsProjectionCompilesAt
    {recordedArguments external currentArguments restArguments outer localBefore localAfter
      boundary recordedSourceWires recordedTargetWires : List Sig}
    {signature : Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (current : Vars external currentArguments)
    (head : Var external signature) (tail : Vars external restArguments)
    {pending : Region outer}
    (request : Telescope.Request
      (argumentNormalizedRegionAt recordedSites current) pending)
    (pendingIso : RegionIso (WireEquiv.refl outer) pending
      (argumentNormalizedRegionAt recordedSites
        (Theory.Vars.extend current (Theory.Vars.cons head tail))))
    (baseCanonical : (request.occurrence.context.fill
      (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))).Canonical)
    (baseExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      request.occurrence.interface.boundaryWire
      (request.occurrence.context.fill (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external)))) :
    request.Result := by
  let first := Theory.Vars.extend current
    (Theory.Vars.cons head Theory.Vars.nil)
  have firstValidity := argumentAppendValidityAt recordedSites current head
    request.occurrence.interface request.occurrence.context
    request.instantiatedCanonical request.instantiatedExternalTwoEnded
  let prepare : request.Preparation
      (argumentNormalizedRegionAt recordedSites current) := {
    prepared := argumentNormalizedRegionAt recordedSites current
    preparedCanonical := request.instantiatedCanonical
    preparedExternalTwoEnded := request.instantiatedExternalTwoEnded
    rawPreparedCanonical := request.instantiatedCanonical
    rawPreparedExternalTwoEnded := request.instantiatedExternalTwoEnded
    preparedIso := RegionIso.refl _
    telescope := Telescope.refl request.polarity request.occurrence.interface
      request.occurrence.context request.instantiatedCanonical
      request.instantiatedExternalTwoEnded request.continuation.1
  }
  cases tail with
  | nil =>
      let singletonPresentation := argumentNormalizationPresentationAt
        recordedSites (Theory.Vars.extend current
          (Theory.Vars.cons head Theory.Vars.nil))
          (Theory.Vars.extend current
            (Theory.Vars.cons head Theory.Vars.nil)) rfl HEq.rfl
      exact argumentProjectionNormalizedAt recordedSites current head request
        (pendingIso.trans singletonPresentation) prepare
  | @cons nextSignature nextRest nextHead nextTail =>
      let remaining := Theory.Vars.cons nextHead nextTail
      let nestedFinal := Theory.Vars.extend first remaining
      have assocEq : HEq nestedFinal
          (Theory.Vars.extend current
            (Theory.Vars.cons head remaining)) := by
        exact Theory.Vars.extend_assoc current
          (Theory.Vars.cons head Theory.Vars.nil) remaining
      let associationPresentation := argumentNormalizationPresentationAt
        recordedSites
        (Theory.Vars.extend current (Theory.Vars.cons head remaining))
        nestedFinal (List.append_assoc currentArguments [signature]
          (nextSignature :: nextRest)).symm assocEq.symm
      let stageInterface : OpenDiagram request.boundary :=
        request.occurrence.interface
      let stageContext : DiagramContext stageInterface.external outer :=
        request.occurrence.context
      have recursiveSourceCanonical : (stageContext.fill
          (polaritySource request.polarity
            (argumentNormalizedRegionAt recordedSites first)
            request.endpoint)).Canonical := by
        exact match request.polarity with
          | .positive => by simpa only [stageContext] using firstValidity.1
          | .negative => by
              simpa only [stageContext] using request.endpointCanonical
      have recursiveSourceExternal : OpenDiagram.ExternalTwoEnded
          stageInterface.boundaryWire (stageContext.fill
            (polaritySource request.polarity
              (argumentNormalizedRegionAt recordedSites first)
              request.endpoint)) := by
        exact match request.polarity with
          | .positive => by
              simpa only [stageInterface, stageContext] using firstValidity.2
          | .negative => by
              simpa only [stageInterface, stageContext] using
                request.endpointExternalTwoEnded
      let recursiveRequest : Telescope.Request
          (argumentNormalizedRegionAt recordedSites first) pending := {
        boundary := request.boundary
        source := stageInterface.withBody
          (stageContext.fill (polaritySource request.polarity
            (argumentNormalizedRegionAt recordedSites first) request.endpoint))
          recursiveSourceCanonical recursiveSourceExternal
        endpoint := request.endpoint
        polarity := request.polarity
        occurrence := exactOccurrence stageInterface
          stageContext (polaritySource request.polarity
            (argumentNormalizedRegionAt recordedSites first) request.endpoint)
          recursiveSourceCanonical recursiveSourceExternal
        instantiatedCanonical := firstValidity.1
        instantiatedExternalTwoEnded := firstValidity.2
        pendingCanonical := request.pendingCanonical
        pendingExternalTwoEnded := request.pendingExternalTwoEnded
        endpointCanonical := request.endpointCanonical
        endpointExternalTwoEnded := request.endpointExternalTwoEnded
        continuation := request.continuation
      }
      have recursiveCompiled := argumentVarsProjectionCompilesAt
        (boundary := request.boundary) recordedSites
        first nextHead nextTail recursiveRequest
        (pendingIso.trans associationPresentation) baseCanonical
        baseExternalTwoEnded
      have recursiveTelescope := Telescope.StrictDerives.toTelescope
        request.polarity request.occurrence.interface request.occurrence.context
        firstValidity.1 firstValidity.2 request.endpointCanonical
        request.endpointExternalTwoEnded request.continuation.1
        recursiveCompiled
      let firstRequest : Telescope.Request
          (argumentNormalizedRegionAt recordedSites current)
          (argumentNormalizedRegionAt recordedSites first) := {
        boundary := request.boundary
        source := request.source
        endpoint := request.endpoint
        polarity := request.polarity
        occurrence := request.occurrence
        instantiatedCanonical := request.instantiatedCanonical
        instantiatedExternalTwoEnded := request.instantiatedExternalTwoEnded
        pendingCanonical := firstValidity.1
        pendingExternalTwoEnded := firstValidity.2
        endpointCanonical := request.endpointCanonical
        endpointExternalTwoEnded := request.endpointExternalTwoEnded
        continuation := recursiveTelescope
      }
      let firstPrepare : firstRequest.Preparation
          (argumentNormalizedRegionAt recordedSites current) := {
        prepared := prepare.prepared
        preparedCanonical := prepare.preparedCanonical
        preparedExternalTwoEnded := prepare.preparedExternalTwoEnded
        rawPreparedCanonical := prepare.rawPreparedCanonical
        rawPreparedExternalTwoEnded := prepare.rawPreparedExternalTwoEnded
        preparedIso := prepare.preparedIso
        telescope := prepare.telescope
      }
      exact argumentProjectionNormalizedAt recordedSites current head firstRequest
        (RegionIso.refl _) firstPrepare

theorem argumentNormalizationTelescopeAt
    {recordedArguments external outer localBefore localAfter boundary : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments
      (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (positionalValues : Vars external recordedArguments)
    (externalNonempty : external ≠ [])
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    {positionalPending endpoint : Region outer}
    (positionalEq : positionalPending =
      argumentNormalizedRegionAt recordedSites positionalValues)
    (positionalCanonical : (context.fill positionalPending).Canonical)
    (positionalExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill positionalPending))
    (authoritativeCanonical :
      (context.fill (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))).Canonical)
    (authoritativeExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire
      (context.fill (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))))
    (endpointCanonical : (context.fill endpoint).Canonical)
    (endpointExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill endpoint))
    (polarity : Polarity) (polarityEq : context.polarity = polarity)
    (continuation : Telescope polarity interface context
      (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external)) endpoint
      authoritativeCanonical authoritativeExternalTwoEnded endpointCanonical
      endpointExternalTwoEnded) :
    Telescope polarity interface context positionalPending endpoint
      positionalCanonical positionalExternalTwoEnded endpointCanonical
      endpointExternalTwoEnded := by
  let authoritativeValues := EqualityNormalization.formalPorts external
  let extendedValues := Theory.Vars.extend positionalValues authoritativeValues
  let extendedPending := argumentNormalizedRegionAt recordedSites extendedValues
  have extendedValidity := argumentExtendedValidityAt recordedSites
    positionalValues interface context authoritativeCanonical
      authoritativeExternalTwoEnded
  have contractTelescope : Telescope polarity interface context
      extendedPending endpoint extendedValidity.1 extendedValidity.2
      endpointCanonical endpointExternalTwoEnded := by
    simpa only [extendedPending, extendedValues, authoritativeValues] using
      argumentVarsContractTelescopeAt recordedSites positionalValues interface
        context authoritativeCanonical authoritativeExternalTwoEnded
        endpointCanonical endpointExternalTwoEnded polarity polarityEq
        continuation
  have positionalNormalizedCanonical :
      (context.fill
        (argumentNormalizedRegionAt recordedSites positionalValues)).Canonical :=
    positionalEq ▸ positionalCanonical
  have positionalNormalizedExternal : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire
      (context.fill (argumentNormalizedRegionAt recordedSites positionalValues)) :=
    positionalEq ▸ positionalExternalTwoEnded
  have positionalSourceCanonical :
      (context.fill (polaritySource polarity positionalPending endpoint)).Canonical := by
    cases polarity
    · exact positionalCanonical
    · exact endpointCanonical
  have positionalSourceExternal : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire
      (context.fill (polaritySource polarity positionalPending endpoint)) := by
    intro signature wire
    cases polarity
    · exact positionalExternalTwoEnded wire
    · exact endpointExternalTwoEnded wire
  let positionalSource := interface.withBody
    (context.fill (polaritySource polarity positionalPending endpoint))
    positionalSourceCanonical positionalSourceExternal
  have normalizedSourceCanonical :
      (context.fill (polaritySource polarity
        (argumentNormalizedRegionAt recordedSites positionalValues)
        endpoint)).Canonical := by
    cases polarity
    · exact positionalNormalizedCanonical
    · exact endpointCanonical
  have normalizedSourceExternal : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire
      (context.fill (polaritySource polarity
        (argumentNormalizedRegionAt recordedSites positionalValues)
        endpoint)) := by
    intro signature wire
    cases polarity
    · exact positionalNormalizedExternal wire
    · exact endpointExternalTwoEnded wire
  let normalizedOccurrence : Occurrence
      (polaritySource polarity
        (argumentNormalizedRegionAt recordedSites positionalValues) endpoint)
      positionalSource := {
    interface := interface
    context := context
    sourceCanonical := normalizedSourceCanonical
    sourceExternalTwoEnded := normalizedSourceExternal
    host_iso := by
      cases polarity with
      | positive =>
          simpa only [positionalSource, polaritySource] using
            OpenDiagram.withBody_iso positionalCanonical
              positionalNormalizedCanonical positionalExternalTwoEnded
              positionalNormalizedExternal
              (DiagramContext.fillIso context (RegionIso.ofEq positionalEq))
      | negative =>
          simpa only [positionalSource, polaritySource] using
            OpenDiagramIso.refl
              (interface.withBody (context.fill endpoint) endpointCanonical
                endpointExternalTwoEnded)
  }
  let projectionRequest : Telescope.Request
      (argumentNormalizedRegionAt recordedSites positionalValues)
      extendedPending := {
    boundary := boundary
    source := positionalSource
    endpoint := endpoint
    polarity := polarity
    occurrence := normalizedOccurrence
    instantiatedCanonical := positionalNormalizedCanonical
    instantiatedExternalTwoEnded := positionalNormalizedExternal
    pendingCanonical := extendedValidity.1
    pendingExternalTwoEnded := extendedValidity.2
    endpointCanonical := endpointCanonical
    endpointExternalTwoEnded := endpointExternalTwoEnded
    continuation := contractTelescope
  }
  have projectionCompiled : projectionRequest.Result := by
    obtain ⟨authoritativeSignature, authoritativeRest, authoritativeHead,
        authoritativeTail, authoritativeArgumentsEq,
        authoritativeValuesEq⟩ :=
      EqualityNormalization.formalPorts_cons_of_nonempty externalNonempty
    let extendedCons := Theory.Vars.extend positionalValues
      (Theory.Vars.cons authoritativeHead authoritativeTail)
    have extendedArgumentsEq :
        recordedArguments ++ external =
          recordedArguments ++ (authoritativeSignature :: authoritativeRest) :=
      congrArg (List.append recordedArguments) authoritativeArgumentsEq
    have extendedValuesEq : HEq extendedValues extendedCons := by
      exact varsExtendHEqRight positionalValues authoritativeValues
        (Theory.Vars.cons authoritativeHead authoritativeTail)
        authoritativeArgumentsEq authoritativeValuesEq
    let pendingIso := argumentNormalizationPresentationAt recordedSites
      extendedValues extendedCons extendedArgumentsEq extendedValuesEq
    exact argumentVarsProjectionCompilesAt (boundary := boundary) recordedSites
      positionalValues authoritativeHead authoritativeTail projectionRequest
      pendingIso authoritativeCanonical authoritativeExternalTwoEnded
  have optional : ∀ {first last : OpenDiagram boundary},
      Relation.TransGen Step first last → Relation.ReflTransGen Step first last := by
    intro first last steps
    induction steps with
    | single step => exact .tail .refl step
    | tail _ step induction => exact .tail induction step
  cases polarity with
  | positive =>
      have exactCompiled : Relation.TransGen Step
          (interface.withBody (context.fill positionalPending)
            positionalCanonical positionalExternalTwoEnded)
          (interface.withBody (context.fill endpoint)
            endpointCanonical endpointExternalTwoEnded) := by
        simpa [projectionRequest, normalizedOccurrence, positionalSource,
          exactOccurrence, polaritySource, polarityTarget] using
            projectionCompiled
      exact ⟨polarityEq, optional exactCompiled⟩
  | negative =>
      let targetIso : OpenDiagramIso
          (interface.withBody
            (context.fill
              (argumentNormalizedRegionAt recordedSites positionalValues))
            positionalNormalizedCanonical positionalNormalizedExternal)
          (interface.withBody (context.fill positionalPending)
            positionalCanonical positionalExternalTwoEnded) :=
        OpenDiagram.withBody_iso positionalNormalizedCanonical
          positionalCanonical positionalNormalizedExternal
          positionalExternalTwoEnded
          (DiagramContext.fillIso context (RegionIso.ofEq positionalEq.symm))
      have exactCompiled : Relation.TransGen Step
          (interface.withBody (context.fill endpoint)
            endpointCanonical endpointExternalTwoEnded)
          (interface.withBody
            (context.fill
              (argumentNormalizedRegionAt recordedSites positionalValues))
            positionalNormalizedCanonical positionalNormalizedExternal) := by
        simpa [projectionRequest, normalizedOccurrence, positionalSource,
          exactOccurrence, polaritySource, polarityTarget] using
            projectionCompiled
      exact ⟨polarityEq, optional (transGen_iso
        (OpenDiagramIso.refl _) exactCompiled targetIso)⟩

/-- Argument normalization including the structurally empty boundary case,
where the positional and authoritative tuples are both empty and no argument
step is required. -/
theorem argumentNormalizationTelescopeAllAt
    {recordedArguments external outer localBefore localAfter boundary : List Sig}
    {recordedPattern : OpenDiagram recordedArguments}
    {recordedOperation : Transform.Operation recordedArguments}
    {recordedFrame : Transform.Frame recordedArguments
      (outer ++ (localBefore ++ localAfter))
      recordedSourceWires recordedTargetWires}
    {recordedData : recordedOperation.Data recordedFrame}
    {recordedSource : ItemSeq recordedSourceWires}
    {recordedResult : Region (outer ++ (localBefore ++ localAfter))}
    {recordedEvidence :
      VisualProof.Rule.Comprehension.Instantiation.ItemsResult
        recordedPattern recordedFrame.sourceKeep recordedFrame.selected
        recordedSource recordedResult}
    (recordedSites : ItemsSites
      (recordingOperation recordedOperation external) recordedData
      recordedEvidence)
    (positionalValues : Vars external recordedArguments)
    (interface : OpenDiagram boundary)
    (context : DiagramContext interface.external outer)
    {positionalPending endpoint : Region outer}
    (positionalEq : positionalPending =
      argumentNormalizedRegionAt recordedSites positionalValues)
    (positionalCanonical : (context.fill positionalPending).Canonical)
    (positionalExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill positionalPending))
    (authoritativeCanonical :
      (context.fill (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))).Canonical)
    (authoritativeExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire
      (context.fill (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external))))
    (endpointCanonical : (context.fill endpoint).Canonical)
    (endpointExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      interface.boundaryWire (context.fill endpoint))
    (polarity : Polarity) (polarityEq : context.polarity = polarity)
    (continuation : Telescope polarity interface context
      (argumentNormalizedRegionAt recordedSites
        (EqualityNormalization.formalPorts external)) endpoint
      authoritativeCanonical authoritativeExternalTwoEnded endpointCanonical
      endpointExternalTwoEnded) :
    Telescope polarity interface context positionalPending endpoint
      positionalCanonical positionalExternalTwoEnded endpointCanonical
      endpointExternalTwoEnded := by
  cases external with
  | nil =>
      cases positionalValues with
      | nil =>
          simpa only [positionalEq, EqualityNormalization.formalPorts,
            Erasure.Exposure.identityBoundary] using continuation
      | cons head tail => exact nomatch head
  | cons signature rest =>
      exact argumentNormalizationTelescopeAt recordedSites positionalValues
        (by simp) interface context positionalEq positionalCanonical
        positionalExternalTwoEnded authoritativeCanonical
        authoritativeExternalTwoEnded endpointCanonical
        endpointExternalTwoEnded polarity polarityEq continuation


end VisualProof.Rule.Completeness.Comprehension
