import VisualProof.Sig

namespace VisualProof

universe u

namespace PreModel

/-- A tuple over arbitrary signature-indexed domains. -/
def Args (Domain : Sig → Type u) : List Sig → Type u
  | [] => PUnit
  | sig :: rest => Domain sig × Args Domain rest

/-- Convert a tuple over full domains to the recursive full-domain tuple. -/
def Args.toFull :
    {sigs : List Sig} →
    Args (Sig.denote Carrier) sigs → Sig.Args Carrier sigs
  | [], PUnit.unit => PUnit.unit
  | _ :: _, ⟨head, tail⟩ => ⟨head, Args.toFull tail⟩

/-- Convert a recursive full-domain tuple to a generic model tuple. -/
def Args.ofFull :
    {sigs : List Sig} →
    Sig.Args Carrier sigs → Args (Sig.denote Carrier) sigs
  | [], PUnit.unit => PUnit.unit
  | _ :: _, ⟨head, tail⟩ => ⟨head, Args.ofFull tail⟩

@[simp] theorem Args.toFull_ofFull
    (values : Sig.Args Carrier sigs) :
    Args.toFull (Args.ofFull values) = values := by
  induction sigs with
  | nil =>
      cases values
      rfl
  | cons _ rest ih =>
      rcases values with ⟨head, tail⟩
      simp only [Args.ofFull, Args.toFull]
      exact congrArg (fun value => (head, value)) (ih tail)

@[simp] theorem Args.ofFull_toFull
    (values : Args (Sig.denote Carrier) sigs) :
    Args.ofFull (Args.toFull values) = values := by
  induction sigs with
  | nil =>
      cases values
      rfl
  | cons _ rest ih =>
      rcases values with ⟨head, tail⟩
      simp only [Args.toFull, Args.ofFull]
      exact congrArg (fun value => (head, value)) (ih tail)

end PreModel

/-- A generic signature-indexed applicative model. -/
structure PreModel where
  Domain : Sig → Type u
  inhabited : (sig : Sig) → Nonempty (Domain sig)
  apply :
    {args : List Sig} →
    Domain (.rel args) → PreModel.Args Domain args → Prop

/-- A full higher-order model generated by one nonempty individual carrier. -/
structure Model where
  Carrier : Type u
  inhabited : Nonempty Carrier

namespace Model

/-- Forget fullness while retaining the canonical application operation. -/
def toPreModel (model : Model) : PreModel where
  Domain := Sig.denote model.Carrier
  inhabited := Sig.denote_nonempty model.inhabited
  apply relation arguments := relation (PreModel.Args.toFull arguments)

/-- Full relation domains contain every predicate on the matching tuple. -/
theorem reify (model : Model) (P : Sig.Args model.Carrier args → Prop) :
    ∃ relation : Sig.denote model.Carrier (.rel args),
      ∀ values, relation values ↔ P values :=
  ⟨P, fun _ => Iff.rfl⟩

end Model

/-- A typed environment for a signature context. -/
def Env (model : PreModel) (ctx : List Sig) : Type u :=
  (sig : Sig) → Var ctx sig → model.Domain sig

namespace Env

/-- Extend an environment with one value at the head of its context. -/
def extend (env : Env model ctx) (value : model.Domain sig) :
    Env model (sig :: ctx)
  | _, .here => value
  | _, .there var => env _ var

@[simp] theorem extend_here
    (env : Env model ctx) (value : model.Domain sig) :
    extend env value sig .here = value := rfl

@[simp] theorem extend_there
    (env : Env model ctx) (value : model.Domain head)
    (var : Var ctx sig) :
    extend env value sig (.there var) = env sig var := rfl

/-- Combine environments for contexts concatenated in order. -/
def append :
    {left : List Sig} →
    Env model left → Env model right → Env model (left ++ right)
  | [], _, rightEnv => rightEnv
  | _ :: _, leftEnv, rightEnv =>
      fun sig var =>
        match var with
        | .here => leftEnv _ .here
        | .there rest =>
            append
              (fun sig var => leftEnv sig (.there var))
              rightEnv sig rest

@[simp] theorem append_left
    (leftEnv : Env model left) (rightEnv : Env model right)
    (var : Var left sig) :
    append leftEnv rightEnv sig (var.appendLeft right) = leftEnv sig var := by
  induction var with
  | here => rfl
  | there var ih =>
      simp only [Var.appendLeft, append]
      exact ih (fun sig var => leftEnv sig (.there var))

@[simp] theorem append_right
    (leftEnv : Env model left) (rightEnv : Env model right)
    (var : Var right sig) :
    append leftEnv rightEnv sig (Var.appendRight left var) = rightEnv sig var := by
  induction left with
  | nil => rfl
  | cons _ tail ih =>
      simp only [Var.appendRight, append]
      exact ih (fun sig var => leftEnv sig (.there var))

end Env

namespace Vars

/-- Read an ordered tuple of variables from a typed environment. -/
def denote (env : Env model ctx) :
    Vars ctx sigs → PreModel.Args model.Domain sigs
  | .nil => PUnit.unit
  | .cons var rest => ⟨env _ var, denote env rest⟩

@[simp] theorem denote_nil (env : Env model ctx) :
    denote env (.nil : Vars ctx []) = PUnit.unit := rfl

@[simp] theorem denote_cons
    (env : Env model ctx) (var : Var ctx sig) (rest : Vars ctx sigs) :
    denote env (.cons var rest) = ⟨env sig var, denote env rest⟩ := rfl

end Vars

end VisualProof
