import VisualProof.Lambda.Syntax
import VisualProof.Lambda.Rename
import VisualProof.Lambda.Substitute
import VisualProof.Lambda.Reduction
import VisualProof.Lambda.Certificate
import VisualProof.Lambda.Quotient
import VisualProof.Theory.Signature
import VisualProof.Data.Finite
import VisualProof.Diagram.Core
import VisualProof.Diagram.Boundary
import VisualProof.Diagram.Rename
import VisualProof.Diagram.Semantics
import VisualProof.Diagram.Context
import VisualProof.Diagram.Isomorphism
import VisualProof.Diagram.Concrete
