import { expect, test } from '@playwright/test'

test('renders exact separate tree counts and lets the player walk', async ({ page }) => {
  test.setTimeout(45_000)
  const started = performance.now()
  await page.goto('/?trees=3')

  const orchard = page.locator('[data-orchard]')
  await expect(orchard).toHaveAttribute('data-ready', 'true', { timeout: 30_000 })
  expect(performance.now() - started).toBeLessThan(3000)
  await expect(page).toHaveTitle('Orchard Renderer Stress Test')
  await expect(orchard).toHaveAttribute('data-world-version', '1')
  await expect(orchard).toHaveAttribute('data-saved-tree-count', '2000')
  await expect(orchard).toHaveAttribute('data-tree-count', '3')
  await expect(orchard).toHaveAttribute('data-entity-count', '219')
  await expect(orchard).toHaveAttribute('data-instanced-count', '0')

  const countScale = page.getByRole('slider', { name: 'Tree count scale' })
  await expect(countScale).toHaveValue('3')
  await expect(page.getByText('zeroIsNat · step 20')).toBeVisible()
  await expect(page.getByText('Draw calls')).toBeVisible()

  const before = Number(await orchard.getAttribute('data-player-z'))
  await page.keyboard.down('w')
  await page.waitForTimeout(350)
  await page.keyboard.up('w')
  const after = Number(await orchard.getAttribute('data-player-z'))
  expect(after).toBeLessThan(before - 0.5)

  await page.getByRole('spinbutton', { name: 'Tree count', exact: true }).fill('5')
  await page.getByRole('button', { name: 'Apply tree count' }).click()
  await expect(orchard).toHaveAttribute('data-tree-count', '5')
  await expect(orchard).toHaveAttribute('data-entity-count', '365')
  await expect(orchard).toHaveAttribute('data-instanced-count', '0')

  const countInput = page.getByRole('spinbutton', { name: 'Tree count', exact: true })
  await countScale.fill('10')
  await countScale.dispatchEvent('change')
  await expect(orchard).toHaveAttribute('data-tree-count', '10')
  await expect(countInput).toHaveValue('10')
  await expect(page.locator('[data-status]')).toContainText('10 independent trees · 750 renderer objects')

  const hundredPreset = page.getByRole('button', { name: '100', exact: true })
  await hundredPreset.click()
  await expect(countInput).toBeDisabled()
  await expect(orchard).toHaveAttribute('data-tree-count', '100')
  await expect(countInput).toBeEnabled()
  await expect(countInput).toHaveValue('100')
  await expect(countScale).toHaveValue('100')
  await expect(hundredPreset).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('[data-fps]')).toHaveText(/^\d+(?:\.\d)?$/)
})
