import VisualProof.Diagram.Concrete.IdentityNormalizationPriorityFusionTransition

namespace VisualProof

namespace ConcreteDiagram

open IdentityNormalizationCore

namespace IdentityNormalizationPriority

namespace CollapseQuotient

/-- The equivalence relation generated by contracting the incident carriers of
two selected identities. The cross terms are present exactly when the two
incident classes overlap, which is the transitive closure needed for shared
survivor/absorbed configurations. -/
def Related
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (left right : source.val.WireId) : Prop :=
  let firstIncident := source.val.identityIncidentWires first
  let secondIncident := source.val.identityIncidentWires second
  let overlaps := ∃ wire, wire ∈ firstIncident ∧ wire ∈ secondIncident
  left = right ∨
    (left ∈ firstIncident ∧ right ∈ firstIncident) ∨
    (left ∈ secondIncident ∧ right ∈ secondIncident) ∨
    (overlaps ∧ left ∈ firstIncident ∧ right ∈ secondIncident) ∨
    (overlaps ∧ left ∈ secondIncident ∧ right ∈ firstIncident)

theorem related_refl
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) :
    Related source first second wire wire := by
  exact Or.inl rfl

theorem related_symm
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    {left right : source.val.WireId} :
    Related source first second left right →
      Related source first second right left := by
  simp only [Related]
  rintro (same | firstClass | secondClass | firstSecond | secondFirst)
  · exact Or.inl same.symm
  · exact Or.inr (Or.inl ⟨firstClass.2, firstClass.1⟩)
  · exact Or.inr (Or.inr (Or.inl ⟨secondClass.2, secondClass.1⟩))
  · exact Or.inr (Or.inr (Or.inr (Or.inr
      ⟨firstSecond.1, firstSecond.2.2, firstSecond.2.1⟩)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl
      ⟨secondFirst.1, secondFirst.2.2, secondFirst.2.1⟩)))

theorem related_trans
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    {left middle right : source.val.WireId} :
    Related source first second left middle →
      Related source first second middle right →
        Related source first second left right := by
  simp only [Related]
  rintro (rfl | leftFirst | leftSecond | leftCross | leftReverse)
  · exact fun relation => relation
  · rintro (rfl | rightFirst | rightSecond | rightCross | rightReverse)
    · exact Or.inr (Or.inl leftFirst)
    · exact Or.inr (Or.inl ⟨leftFirst.1, rightFirst.2⟩)
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨⟨middle, leftFirst.2, rightSecond.1⟩,
          leftFirst.1, rightSecond.2⟩)))
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨rightCross.1, leftFirst.1, rightCross.2.2⟩)))
    · exact Or.inr (Or.inl ⟨leftFirst.1, rightReverse.2.2⟩)
  · rintro (rfl | rightFirst | rightSecond | rightCross | rightReverse)
    · exact Or.inr (Or.inr (Or.inl leftSecond))
    · exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨⟨middle, rightFirst.1, leftSecond.2⟩,
          leftSecond.1, rightFirst.2⟩)))
    · exact Or.inr (Or.inr (Or.inl ⟨leftSecond.1, rightSecond.2⟩))
    · exact Or.inr (Or.inr (Or.inl
        ⟨leftSecond.1, rightCross.2.2⟩))
    · exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨rightReverse.1, leftSecond.1, rightReverse.2.2⟩)))
  · rintro (rfl | rightFirst | rightSecond | rightCross | rightReverse)
    · exact Or.inr (Or.inr (Or.inr (Or.inl leftCross)))
    · exact Or.inr (Or.inl ⟨leftCross.2.1, rightFirst.2⟩)
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨leftCross.1, leftCross.2.1, rightSecond.2⟩)))
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨leftCross.1, leftCross.2.1, rightCross.2.2⟩)))
    · exact Or.inr (Or.inl ⟨leftCross.2.1, rightReverse.2.2⟩)
  · rintro (rfl | rightFirst | rightSecond | rightCross | rightReverse)
    · exact Or.inr (Or.inr (Or.inr (Or.inr leftReverse)))
    · exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨leftReverse.1, leftReverse.2.1, rightFirst.2⟩)))
    · exact Or.inr (Or.inr (Or.inl
        ⟨leftReverse.2.1, rightSecond.2⟩))
    · exact Or.inr (Or.inr (Or.inl
        ⟨leftReverse.2.1, rightCross.2.2⟩))
    · exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨leftReverse.1, leftReverse.2.1, rightReverse.2.2⟩)))

/-- The neutral two-collapse equivalence on the original wire carrier. -/
def setoid
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId) : Setoid source.val.WireId where
  r := Related source first second
  iseqv :=
    { refl := related_refl source first second
      symm := related_symm source first second
      trans := related_trans source first second }

/-- Identifier-independent carrier of the neutral two-collapse quotient. -/
abbrev Carrier
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId) : Type :=
  @Quotient source.val.WireId (setoid source first second)

/-- Send an original wire to its neutral two-collapse quotient class. -/
def classOf
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) : Carrier source first second :=
  @Quotient.mk source.val.WireId (setoid source first second) wire

/-- Equality in the neutral carrier is exactly the construction-owned
two-collapse relation. -/
theorem classOf_eq_iff_related
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (left right : source.val.WireId) :
    classOf source first second left = classOf source first second right ↔
      Related source first second left right := by
  constructor
  · intro equal
    exact @Quotient.exact source.val.WireId (setoid source first second)
      left right equal
  · intro related
    exact @Quotient.sound source.val.WireId (setoid source first second)
      left right related

/-- Canonical finite enumeration of a neutral quotient class, in original
wire-carrier order. -/
noncomputable def wireClass
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) : List source.val.WireId :=
  by
    classical
    exact source.val.wiresList.filter fun candidate =>
      decide (Related source first second wire candidate)

theorem mem_wireClass_iff_related
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire candidate : source.val.WireId) :
    candidate ∈ wireClass source first second wire ↔
      Related source first second wire candidate := by
  classical
  simp only [wireClass, List.mem_filter, decide_eq_true_eq]
  constructor
  · exact fun member => member.2
  · exact fun related => ⟨Data.Finite.mem_allFin candidate, related⟩

/-- Every canonical class enumeration contains its representative. -/
theorem wire_mem_wireClass
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) :
    wire ∈ wireClass source first second wire := by
  rw [mem_wireClass_iff_related]
  exact related_refl source first second wire

theorem wireClass_nodup
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) :
    (wireClass source first second wire).Nodup := by
  classical
  unfold wireClass
  exact (Data.Finite.allFin_nodup source.val.wireCount).filter _

/-- Neutral incidence of a source node after both selected contractions,
represented as distinct equivalence classes rather than arm-specific dense
wire identifiers. -/
noncomputable def incidentClasses
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId) :
    List (List source.val.WireId) :=
  ((source.val.identityIncidentWires other).map
    (wireClass source first second)).eraseDups

theorem related_swap
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (left right : source.val.WireId) :
    Related source first second left right ↔
      Related source second first left right := by
  simp only [Related]
  constructor
  · rintro (same | firstClass | secondClass | firstSecond | secondFirst)
    · exact Or.inl same
    · exact Or.inr (Or.inr (Or.inl firstClass))
    · exact Or.inr (Or.inl secondClass)
    · obtain ⟨overlap, leftMember, rightMember⟩ := firstSecond
      exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨⟨overlap.choose, overlap.choose_spec.2,
            overlap.choose_spec.1⟩, leftMember, rightMember⟩)))
    · obtain ⟨overlap, leftMember, rightMember⟩ := secondFirst
      exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨⟨overlap.choose, overlap.choose_spec.2,
            overlap.choose_spec.1⟩, leftMember, rightMember⟩)))
  · rintro (same | secondClass | firstClass | secondFirst | firstSecond)
    · exact Or.inl same
    · exact Or.inr (Or.inr (Or.inl secondClass))
    · exact Or.inr (Or.inl firstClass)
    · obtain ⟨overlap, leftMember, rightMember⟩ := secondFirst
      exact Or.inr (Or.inr (Or.inr (Or.inr
        ⟨⟨overlap.choose, overlap.choose_spec.2,
            overlap.choose_spec.1⟩, leftMember, rightMember⟩)))
    · obtain ⟨overlap, leftMember, rightMember⟩ := firstSecond
      exact Or.inr (Or.inr (Or.inr (Or.inl
        ⟨⟨overlap.choose, overlap.choose_spec.2,
            overlap.choose_spec.1⟩, leftMember, rightMember⟩)))

theorem wireClass_swap
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (wire : source.val.WireId) :
    wireClass source first second wire =
      wireClass source second first wire := by
  unfold wireClass
  apply List.filter_congr
  intro candidate _
  rw [decide_eq_decide]
  exact related_swap source first second wire candidate

/-- The neutral quotient incidence is independent of the chosen first arm. -/
theorem incidentClasses_swap
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId) :
    incidentClasses source first second other =
      incidentClasses source second first other := by
  unfold incidentClasses
  apply congrArg List.eraseDups
  apply List.map_congr_left
  intro wire _
  exact wireClass_swap source first second wire

theorem wireClass_eq_of_related
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    {left right : source.val.WireId}
    (related : Related source first second left right) :
    wireClass source first second left =
      wireClass source first second right := by
  classical
  unfold wireClass
  apply List.filter_congr
  intro candidate _
  rw [decide_eq_decide]
  constructor
  · exact fun leftRelated =>
      related_trans source first second (related_symm source first second related)
        leftRelated
  · exact fun rightRelated =>
      related_trans source first second related rightRelated

/-- Canonical finite class representatives are equal exactly when their
quotient classes are equal. -/
theorem wireClass_eq_iff_related
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (left right : source.val.WireId) :
    wireClass source first second left =
        wireClass source first second right ↔
      Related source first second left right := by
  constructor
  · intro classesEqual
    have member : left ∈ wireClass source first second right := by
      rw [← classesEqual]
      exact wire_mem_wireClass source first second left
    exact related_symm source first second
      ((mem_wireClass_iff_related source first second right left).mp member)
  · exact wireClass_eq_of_related source first second

theorem related_representative
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (eligible : CollapseEligibility source first)
    (wire : source.val.WireId) :
    Related source first second wire
      (IdentityNormalizationCollapseSemantics.representative source first
        eligible wire) := by
  unfold IdentityNormalizationCollapseSemantics.representative
  split
  · rename_i incident
    apply Or.inr
    apply Or.inl
    constructor
    · exact incident
    · rw [← mem_collapseIncidentWires source first eligible.identity.region]
      rw [eligible.incident_eq]
      simp
  · exact related_refl source first second wire

theorem wireClass_representative
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (eligible : CollapseEligibility source first)
    (wire : source.val.WireId) :
    wireClass source first second
        (IdentityNormalizationCollapseSemantics.representative source first
          eligible wire) =
      wireClass source first second wire :=
  (wireClass_eq_of_related source first second
    (related_representative source first second eligible wire)).symm

/-- Neutral class assigned to a dense wire after taking the named first arm. -/
noncomputable def armWireClass
    (source : CheckedDiagram definitions)
    (first second : source.val.NodeId)
    (eligible : CollapseEligibility source first)
    (wire : (CollapseTransition.Target source first eligible).val.WireId) :
    List source.val.WireId :=
  wireClass source first second
    (collapseSourceWire source first eligible wire)

/-- Neutral incidence observed from one first-collapse arm. -/
noncomputable def armIncidentClasses
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId)
    (eligible : CollapseEligibility source first)
    (different : other ≠ first) : List (List source.val.WireId) :=
  (((CollapseTransition.Target source first eligible).val.identityIncidentWires
      (CollapseTransition.retainedNode source first other eligible different)).map
    (armWireClass source first second eligible)).eraseDups

/-- Every first-collapse arm maps a surviving identity's incidence to exactly
the neutral two-collapse equivalence classes. -/
theorem mem_armIncidentClasses_iff
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId)
    (eligible : CollapseEligibility source first)
    (different : other ≠ first)
    (classValue : List source.val.WireId) :
    classValue ∈ armIncidentClasses source first second other eligible different ↔
      classValue ∈ incidentClasses source first second other := by
  classical
  simp only [armIncidentClasses, incidentClasses, List.mem_eraseDups,
    List.mem_map]
  constructor
  · rintro ⟨targetWire, targetIncident, classExact⟩
    obtain ⟨sourceWire, sourceIncident, quotientExact⟩ :=
      (CollapseTransition.mem_identityIncidentWires_iff_exists_quotient
        source first other eligible different targetWire).mp targetIncident
    refine ⟨sourceWire, sourceIncident, ?_⟩
    have sourceOrigin :
        collapseSourceWire source first eligible targetWire =
          IdentityNormalizationCollapseSemantics.representative source first
            eligible sourceWire := by
      change
        IdentityNormalizationCollapseSemantics.sourceWire source first eligible
            targetWire = _
      rw [← quotientExact]
      exact IdentityNormalizationCollapseSemantics.sourceWire_targetWire
        source first eligible sourceWire
    rw [← classExact]
    unfold armWireClass
    rw [sourceOrigin]
    exact (wireClass_representative source first second eligible sourceWire).symm
  · rintro ⟨sourceWire, sourceIncident, classExact⟩
    let targetWire :=
      IdentityNormalizationCollapseSemantics.targetWire source first eligible
        sourceWire
    have targetIncident : targetWire ∈
        (CollapseTransition.Target source first eligible).val.identityIncidentWires
          (CollapseTransition.retainedNode source first other eligible
            different) :=
      (CollapseTransition.mem_identityIncidentWires_iff_exists_quotient
        source first other eligible different targetWire).mpr
        ⟨sourceWire, sourceIncident, rfl⟩
    refine ⟨targetWire, targetIncident, ?_⟩
    rw [← classExact]
    unfold armWireClass targetWire
    change wireClass source first second
        (IdentityNormalizationCollapseSemantics.sourceWire source first eligible
          (IdentityNormalizationCollapseSemantics.targetWire source first
            eligible sourceWire)) = _
    rw [IdentityNormalizationCollapseSemantics.sourceWire_targetWire]
    exact wireClass_representative source first second eligible sourceWire

/-- Both first-collapse arms induce the same neutral incidence classes for
every node that survives both selected contractions. -/
theorem armIncidentClasses_mem_iff_swapped
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId)
    (firstEligible : CollapseEligibility source first)
    (secondEligible : CollapseEligibility source second)
    (otherNeFirst : other ≠ first)
    (otherNeSecond : other ≠ second)
    (classValue : List source.val.WireId) :
    classValue ∈ armIncidentClasses source first second other firstEligible
        otherNeFirst ↔
      classValue ∈ armIncidentClasses source second first other secondEligible
        otherNeSecond := by
  rw [mem_armIncidentClasses_iff, mem_armIncidentClasses_iff]
  rw [incidentClasses_swap source first second other]

/-- The two possible first-collapse arms expose permutation-equal neutral
incidence carriers at every node surviving both contractions. -/
theorem armIncidentClasses_perm_swapped
    (source : CheckedDiagram definitions)
    (first second other : source.val.NodeId)
    (firstEligible : CollapseEligibility source first)
    (secondEligible : CollapseEligibility source second)
    (otherNeFirst : other ≠ first)
    (otherNeSecond : other ≠ second) :
    (armIncidentClasses source first second other firstEligible
        otherNeFirst).Perm
      (armIncidentClasses source second first other secondEligible
        otherNeSecond) := by
  apply Data.Finite.list_perm_of_nodup_mem_iff
  · unfold armIncidentClasses
    exact Data.Finite.eraseDups_nodup _
  · unfold armIncidentClasses
    exact Data.Finite.eraseDups_nodup _
  · exact armIncidentClasses_mem_iff_swapped source first second other
      firstEligible secondEligible otherNeFirst otherNeSecond

end CollapseQuotient

end IdentityNormalizationPriority

end ConcreteDiagram

end VisualProof
