import VisualProof.Diagram.Concrete.WireQuantifierRelationJoinRawWireOrigins

namespace VisualProof

namespace ConcreteWireQuantifier

variable {definitions : List (List Sig)}
variable {source : CheckedDiagram definitions}
variable {dying : source.val.WireId}
variable {content : CheckedOpenDiagram definitions}

open RelationJoinResult

/-- An allocation-neutral endpoint: the node is an origin, while the port is
the semantic port carried unchanged by every raw construction step. -/
structure RawEndpoint (Node : Type) where
  node : Node
  port : CPort
  deriving Repr, DecidableEq

/-- Allocation-neutral nodes generated by one checked splice. -/
inductive StepGeneratedNodeOrigin
    (step : RelationJoinStep source dying content) : Type
  | fragment (node : content.val.diagram.NodeId)
  | request (request : Fin step.attachment.identityRequests.length)
  deriving Repr, DecidableEq

abbrev StepGeneratedEndpointOrigin
    (step : RelationJoinStep source dying content) :=
  RawEndpoint (StepGeneratedNodeOrigin step)

/-- Realize one allocation-neutral generated incidence in the attachment's
fresh node carrier. -/
def realizeStepGeneratedEndpoint
    (step : RelationJoinStep source dying content) :
    StepGeneratedEndpointOrigin step →
      CEndpoint step.attachment.nodeCount
  | ⟨.fragment node, port⟩ =>
      ⟨step.attachment.fragmentNode node, port⟩
  | ⟨.request request, port⟩ =>
      ⟨step.attachment.identityNode request, port⟩

/-- The independent copied-fragment incidence stream for one splice. -/
def expectedStepFragmentEndpointOccurrences
    (step : RelationJoinStep source dying content) :
    List (step.attachment.diagram.WireId ×
      StepGeneratedEndpointOrigin step) :=
  content.val.diagram.endpointOccurrences.map fun occurrence =>
    (step.attachment.fragmentWire occurrence.1,
      { node := .fragment occurrence.2.node
        port := occurrence.2.port })

/-- The independent generated-request incidence stream for one splice. -/
def expectedStepRequestEndpointOccurrences
    (step : RelationJoinStep source dying content) :
    List (step.attachment.diagram.WireId ×
      StepGeneratedEndpointOrigin step) :=
  (Data.Finite.allFin step.attachment.identityRequests.length).flatMap
    fun request =>
      let requestData := step.attachment.identityRequests.get request
      (Data.Finite.allFin requestData.attachments.length).map fun port =>
        (step.attachment.hostWire (requestData.attachments.get port),
          { node := .request request
            port := .identity port.val })

/-- The independent generated incidence stream for one splice: copied
fragment incidences first, followed by request incidences in request/port
order. -/
def expectedStepGeneratedEndpointOccurrences
    (step : RelationJoinStep source dying content) :
    List (step.attachment.diagram.WireId ×
      StepGeneratedEndpointOrigin step) :=
  expectedStepFragmentEndpointOccurrences step ++
    expectedStepRequestEndpointOccurrences step

/-- Ordered generated endpoint fiber of one attachment wire, expressed only
in allocation-neutral generated-node origins. -/
def expectedStepGeneratedEndpoints
    (step : RelationJoinStep source dying content)
    (wire : step.attachment.diagram.WireId) :
    List (StepGeneratedEndpointOrigin step) :=
  (expectedStepGeneratedEndpointOccurrences step).filterMap fun occurrence =>
    if occurrence.1 = wire then some occurrence.2 else none

private theorem map_filterMap_realize
    (step : RelationJoinStep source dying content)
    (occurrences : List (step.attachment.diagram.WireId ×
      StepGeneratedEndpointOrigin step))
    (wire : step.attachment.diagram.WireId) :
    ((occurrences.filterMap fun occurrence =>
        if occurrence.1 = wire then some occurrence.2 else none).map
      (realizeStepGeneratedEndpoint step)) =
      ((occurrences.map fun occurrence =>
        (occurrence.1, realizeStepGeneratedEndpoint step occurrence.2)).filterMap
          fun occurrence =>
            if occurrence.1 = wire then some occurrence.2 else none) := by
  induction occurrences with
  | nil => rfl
  | cons occurrence rest induction =>
      cases occurrence with
      | mk occurrenceWire occurrenceEndpoint =>
          by_cases same : occurrenceWire = wire <;>
            simp [same, induction]

/-- The independent generated-origin stream realizes exactly to the splice
attachment's authoritative copied-fragment/request stream. -/
theorem expectedStepGeneratedEndpointOccurrences_realize
    (step : RelationJoinStep source dying content) :
    ((expectedStepGeneratedEndpointOccurrences step).map fun occurrence =>
        (occurrence.1, realizeStepGeneratedEndpoint step occurrence.2)) =
      step.attachment.fragmentEndpointOccurrences ++
        step.attachment.identityEndpointOccurrences := by
  rw [expectedStepGeneratedEndpointOccurrences, List.map_append]
  congr 1
  · unfold expectedStepFragmentEndpointOccurrences
      ConcreteSpliceAttachment.fragmentEndpointOccurrences
    rw [List.map_map]
    apply List.map_congr_left
    intro occurrence _
    cases occurrence with
    | mk wire endpoint =>
        cases endpoint
        rfl
  · unfold expectedStepRequestEndpointOccurrences
      ConcreteSpliceAttachment.identityEndpointOccurrences
    rw [List.map_flatMap]
    apply congrArg (fun mapper =>
      List.flatMap mapper
        (Data.Finite.allFin step.attachment.identityRequests.length))
    funext request
    rw [List.map_map]
    apply List.map_congr_left
    intro port _
    rfl

/-- Exact one-splice endpoint theorem: realizing the independent generated
fiber gives precisely the attachment-generated endpoint fiber. -/
theorem expectedStepGeneratedEndpoints_realize
    (step : RelationJoinStep source dying content)
    (wire : step.attachment.diagram.WireId) :
    (expectedStepGeneratedEndpoints step wire).map
        (realizeStepGeneratedEndpoint step) =
      step.attachment.generatedEndpoints wire := by
  rw [expectedStepGeneratedEndpoints,
    map_filterMap_realize,
    expectedStepGeneratedEndpointOccurrences_realize]
  rfl

/-- The checked splice carries the independently specified generated fiber
through the checked endpoint cast without changing its order. -/
theorem checkedWire_generatedEndpoints_exact
    (step : RelationJoinStep source dying content)
    (wire : step.attachment.diagram.WireId) :
    (expectedStepGeneratedEndpoints step wire).map
        (fun endpoint =>
          Internal.checkedEndpoint step.generated
            (realizeStepGeneratedEndpoint step endpoint)) =
      (step.attachment.generatedEndpoints wire).map
        (Internal.checkedEndpoint step.generated) := by
  rw [← expectedStepGeneratedEndpoints_realize step wire]
  change
    List.map
        ((Internal.checkedEndpoint step.generated) ∘
          realizeStepGeneratedEndpoint step)
        (expectedStepGeneratedEndpoints step wire) =
      List.map (Internal.checkedEndpoint step.generated)
        (List.map (realizeStepGeneratedEndpoint step)
          (expectedStepGeneratedEndpoints step wire))
  exact List.map_map.symm

/-- A fresh internal attachment wire has exactly the independently specified
generated fiber after the checked carrier cast. -/
theorem checkedFreshWire_endpoints_exact
    (step : RelationJoinStep source dying content)
    (position : Fin step.attachment.fragmentInternalWires.length) :
    (step.checked.val.wires
        (Internal.checkedWire step.generated
          (step.attachment.freshWire position))).endpoints =
      (expectedStepGeneratedEndpoints step
          (step.attachment.freshWire position)).map
        (fun endpoint =>
          Internal.checkedEndpoint step.generated
            (realizeStepGeneratedEndpoint step endpoint)) := by
  rw [step.checkedAttachmentWire_endpoints]
  unfold ConcreteSpliceAttachment.diagram
    ConcreteSpliceAttachment.wireTable
    ConcreteSpliceAttachment.freshWire
  simp only [Fin.addCases_right]
  exact
    (checkedWire_generatedEndpoints_exact step
      (step.attachment.freshWire position)).symm

/-- Constructive occurrence and internal-position descriptor carried by a
recursive construction-wire origin. -/
structure ConstructionWireDescriptor
    (steps : List (RelationJoinStep source dying content)) where
  occurrence : Fin steps.length
  position : Fin
    ((steps.get occurrence).attachment.fragmentInternalWires.length)

/-- Read the occurrence/position pair encoded by a construction-wire origin
directly from its constructors. -/
def constructionWireDescriptor :
    {steps : List (RelationJoinStep source dying content)} →
      ConstructionWireOrigin steps → ConstructionWireDescriptor steps
  | _ :: _, .head position =>
      { occurrence := 0
        position := by simpa using position }
  | _ :: _, .tail origin =>
      let prior := constructionWireDescriptor origin
      { occurrence := Fin.succ prior.occurrence
        position := by simpa using prior.position }

private def finalContentNodeOrigin
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (occurrence : Fin result.steps.length)
    (node : content.val.diagram.NodeId) : FinalNodeOrigin result :=
  ⟨.inr ⟨occurrence, .inl node⟩, trivial⟩

private def finalRequestNodeOrigin
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (occurrence : Fin result.steps.length)
    (request : Fin
      ((result.steps.get occurrence).attachment.identityRequests.length)) :
    FinalNodeOrigin result :=
  ⟨.inr ⟨occurrence, .inr request⟩, trivial⟩

/-- Retained source incidences of one surviving source wire, in their original
authoritative order, with precisely the consumed applications removed. -/
def expectedSourceWireEndpoints
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (wire : { wire : source.val.WireId // wire ≠ dying }) :
    List (RawEndpoint (FinalNodeOrigin result)) :=
  (source.val.wires wire.1).endpoints.filterMap fun endpoint =>
    if survives : endpoint.node ∉ result.applications then
      some
        { node := ⟨.inl endpoint.node, by
            simpa [PrefixNodeLive, result.steps_application_order] using
              survives⟩
          port := endpoint.port }
    else none

/-- Copied-fragment contribution to one source wire at one occurrence. -/
def expectedSourceFragmentEndpointsAt
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (wire : { wire : source.val.WireId // wire ≠ dying })
    (occurrence : Fin result.steps.length) :
    List (RawEndpoint (FinalNodeOrigin result)) :=
  let step := result.steps.get occurrence
  content.val.diagram.endpointOccurrences.filterMap fun endpointOccurrence =>
    if step.attachment.fragmentWire endpointOccurrence.1 =
        step.attachment.hostWire (step.baseWireImage wire.1) then
      some
        { node := finalContentNodeOrigin result occurrence
            endpointOccurrence.2.node
          port := endpointOccurrence.2.port }
    else none

/-- Generated-request contribution to one source wire at one occurrence. -/
def expectedSourceRequestEndpointsAt
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (wire : { wire : source.val.WireId // wire ≠ dying })
    (occurrence : Fin result.steps.length) :
    List (RawEndpoint (FinalNodeOrigin result)) :=
  let step := result.steps.get occurrence
  (Data.Finite.allFin step.attachment.identityRequests.length).flatMap
    fun request =>
      let requestData := step.attachment.identityRequests.get request
      (Data.Finite.allFin requestData.attachments.length).filterMap fun port =>
        if requestData.attachments.get port = step.baseWireImage wire.1 then
          some
            { node := finalRequestNodeOrigin result occurrence request
              port := .identity port.val }
        else none

/-- Full construction-order fiber of one surviving source wire: retained
source incidences, then copied-fragment and request incidences for every
accepted occurrence. -/
def expectedSurvivingWireEndpoints
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (wire : { wire : source.val.WireId // wire ≠ dying }) :
    List (RawEndpoint (FinalNodeOrigin result)) :=
  expectedSourceWireEndpoints result wire ++
    (Data.Finite.allFin result.steps.length).flatMap fun occurrence =>
      expectedSourceFragmentEndpointsAt result wire occurrence ++
        expectedSourceRequestEndpointsAt result wire occurrence

/-- The copied-fragment fiber of one occurrence-local internal wire. -/
def expectedInternalWireEndpoints
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters)
    (origin : ConstructionWireOrigin result.steps) :
    List (RawEndpoint (FinalNodeOrigin result)) :=
  let descriptor := constructionWireDescriptor origin
  let step := result.steps.get descriptor.occurrence
  content.val.diagram.endpointOccurrences.filterMap fun endpointOccurrence =>
    if step.attachment.fragmentWire endpointOccurrence.1 =
        step.attachment.freshWire descriptor.position then
      some
        { node := finalContentNodeOrigin result descriptor.occurrence
            endpointOccurrence.2.node
          port := endpointOccurrence.2.port }
    else none

/-- Independent authoritative ordered endpoint fiber for every terminal raw
wire origin. -/
def expectedFinalWireEndpoints
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters) :
    FinalWireOrigin result →
      List (RawEndpoint (FinalNodeOrigin result))
  | .inl wire => expectedSurvivingWireEndpoints result wire
  | .inr origin => expectedInternalWireEndpoints result origin

/-- Allocation-neutral endpoint carrier induced by the committed terminal
node-origin equivalence; ports are preserved verbatim. -/
def RelationJoinResult.finalEndpointOriginEquiv
    {parameters : List source.val.WireId}
    (result : RelationJoinResult source dying content parameters) :
    Data.Finite.FiniteEquiv
      (CEndpoint result.plainFinal.val.nodeCount)
      (RawEndpoint (FinalNodeOrigin result)) where
  toFun endpoint :=
    { node := result.finalNodeOriginEquiv endpoint.node
      port := endpoint.port }
  invFun endpoint :=
    { node := result.finalNodeOriginEquiv.symm endpoint.node
      port := endpoint.port }
  left_inv endpoint := by
    cases endpoint with
    | mk node port =>
        congr
        exact result.finalNodeOriginEquiv.left_inv node
  right_inv endpoint := by
    cases endpoint with
    | mk node port =>
        congr
        exact result.finalNodeOriginEquiv.right_inv node

end ConcreteWireQuantifier

end VisualProof
