import VisualProof.Rule.MonolithicWireQuantifierCore

namespace VisualProof

namespace MonolithicWireQuantifier

open ConcreteWireQuantifier

universe u

section Origins

variable {definitions : List (List Sig)}
variable {source : CheckedDiagram definitions}
variable {dying : source.val.WireId}
variable {content : CheckedOpenDiagram definitions}
variable {parameters : List source.val.WireId}

/-- Allocation-neutral origins of raw joined regions.  A content root is not
fresh: it resolves to the retained source region hosting that occurrence. -/
abbrev RelationJoinRawRegionOrigin
    (result : RelationJoinResult source dying content parameters) :=
  source.val.RegionId ⊕
    Σ _occurrence : Fin result.steps.length,
      { region : content.val.diagram.RegionId //
        region ≠ content.val.diagram.root }

/-- Allocation-neutral origins of raw joined nodes.  The final summand is the
dependent family of equality nodes generated by repeated boundary aliases. -/
abbrev RelationJoinRawNodeOrigin
    (result : RelationJoinResult source dying content parameters) :=
  { node : source.val.NodeId // node ∉ result.applications } ⊕
    Σ occurrence : Fin result.steps.length,
      content.val.diagram.NodeId ⊕
        Fin ((result.steps.get occurrence).attachment.identityRequests.length)

/-- Allocation-neutral origins of raw joined wires.  Boundary content wires
are represented by their attachment's retained representative source wire. -/
abbrev RelationJoinRawWireOrigin
    (result : RelationJoinResult source dying content parameters) :=
  { wire : source.val.WireId // wire ≠ dying } ⊕
    Σ _occurrence : Fin result.steps.length,
      { wire : content.val.diagram.WireId //
        wire ∉ content.val.boundary }

/-- Exact raw-region origins in concrete allocation order. -/
def relationJoinRawRegionOrigins
    (result : RelationJoinResult source dying content parameters) :
    List (RelationJoinRawRegionOrigin result) :=
  source.val.regionsList.map Sum.inl ++
    ((Data.Finite.allFin result.steps.length).flatMap fun occurrence =>
      (result.steps.get occurrence).attachment.fragmentRegions.attach.map
        fun region =>
          ⟨occurrence,
            ⟨region.1, by
              have member := List.mem_filter.mp region.2
              exact of_decide_eq_true member.2⟩⟩).map Sum.inr

/-- Exact raw-node origins in concrete allocation order.  Each occurrence's
content nodes precede that splice's generated equality nodes. -/
def relationJoinRawNodeOrigins
    (result : RelationJoinResult source dying content parameters) :
    List (RelationJoinRawNodeOrigin result) :=
  (((source.val.nodesList.filter fun node =>
      decide (node ∉ result.applications)).attach.map fun node =>
        ⟨node.1, of_decide_eq_true (List.mem_filter.mp node.2).2⟩).map
          Sum.inl) ++
    ((Data.Finite.allFin result.steps.length).flatMap fun occurrence =>
      (content.val.diagram.nodesList.map
          (fun node => ⟨occurrence, Sum.inl node⟩) ++
        (Data.Finite.allFin
            ((result.steps.get occurrence).attachment.identityRequests.length)).map
          (fun request => ⟨occurrence, Sum.inr request⟩))).map Sum.inr

/-- Exact raw-wire origins in concrete allocation order. -/
def relationJoinRawWireOrigins
    (result : RelationJoinResult source dying content parameters) :
    List (RelationJoinRawWireOrigin result) :=
  (((source.val.wiresList.filter fun wire => decide (wire ≠ dying)).attach.map
      fun wire =>
        ⟨wire.1, of_decide_eq_true (List.mem_filter.mp wire.2).2⟩).map
          Sum.inl) ++
    ((Data.Finite.allFin result.steps.length).flatMap fun occurrence =>
      ((result.steps.get occurrence).attachment.fragmentInternalWires.attach.map
        fun wire =>
          ⟨occurrence,
            ⟨wire.1, by
              have member := List.mem_filter.mp wire.2
              exact of_decide_eq_true member.2⟩⟩)).map Sum.inr

private theorem nodup_of_map_nodup
    (mapping : α → β) (values : List α)
    (mappedNodup : (values.map mapping).Nodup) :
    values.Nodup := by
  induction values with
  | nil => simp
  | cons head tail induction =>
      rw [List.map_cons, List.nodup_cons] at mappedNodup
      rw [List.nodup_cons]
      refine ⟨?_, induction mappedNodup.2⟩
      intro member
      exact mappedNodup.1 (List.mem_map.mpr ⟨_, member, rfl⟩)

private theorem attach_nodup_of_nodup
    (values : List α) (nodup : values.Nodup) :
    values.attach.Nodup := by
  apply nodup_of_map_nodup Subtype.val values.attach
  change values.attach.unattach.Nodup
  rw [List.unattach_attach]
  exact nodup

private theorem flatMap_nodup_of_disjoint
    {values : List α} {parts : α → List β}
    (valuesNodup : values.Nodup)
    (partsNodup : ∀ value ∈ values, (parts value).Nodup)
    (disjoint : ∀ left ∈ values, ∀ right ∈ values, left ≠ right →
      ∀ first ∈ parts left, ∀ second ∈ parts right, first ≠ second) :
    (values.flatMap parts).Nodup := by
  induction values with
  | nil => simp
  | cons head tail induction =>
      rw [List.nodup_cons] at valuesNodup
      rw [List.flatMap_cons, List.nodup_append]
      refine ⟨partsNodup head (by simp), ?_, ?_⟩
      · exact induction valuesNodup.2
          (by intro value member; exact partsNodup value (by simp [member]))
          (by
            intro left leftMember right rightMember different
            exact disjoint left (by simp [leftMember]) right
              (by simp [rightMember]) different)
      · intro first firstMember second secondMember
        obtain ⟨right, rightMember, secondMember⟩ :=
          List.mem_flatMap.mp secondMember
        exact disjoint head (by simp) right (by simp [rightMember])
          (by intro same; subst right; exact valuesNodup.1 rightMember)
          first firstMember second secondMember

private theorem sumEnumerations_nodup
    (left : List α) (right : List β)
    (leftNodup : left.Nodup) (rightNodup : right.Nodup) :
    (left.map Sum.inl ++ right.map Sum.inr).Nodup := by
  rw [List.nodup_append]
  refine ⟨leftNodup.map _ (by simp), rightNodup.map _ (by simp), ?_⟩
  intro first firstMember second secondMember same
  rcases List.mem_map.mp firstMember with ⟨leftValue, _, rfl⟩
  rcases List.mem_map.mp secondMember with ⟨rightValue, _, rfl⟩
  contradiction

theorem relationJoinRawRegionOrigins_nodup
    (result : RelationJoinResult source dying content parameters) :
    (relationJoinRawRegionOrigins result).Nodup := by
  classical
  apply sumEnumerations_nodup
  · exact Data.Finite.allFin_nodup _
  · apply flatMap_nodup_of_disjoint (Data.Finite.allFin_nodup _)
    · intro occurrence _
      exact (attach_nodup_of_nodup _
        ((Data.Finite.allFin_nodup _).filter _)).map _ (by
          intro left right different equality
          apply different
          apply Subtype.ext
          exact congrArg (fun origin => origin.2.1) equality)
    · intro left _ right _ different first firstMember second secondMember equality
      apply different
      have firstOccurrence : first.1 = left := by
        rcases List.mem_map.mp firstMember with ⟨region, _, rfl⟩
        rfl
      have secondOccurrence : second.1 = right := by
        rcases List.mem_map.mp secondMember with ⟨region, _, rfl⟩
        rfl
      exact firstOccurrence.symm.trans
        ((congrArg Sigma.fst equality).trans secondOccurrence)

theorem relationJoinRawNodeOrigins_nodup
    (result : RelationJoinResult source dying content parameters) :
    (relationJoinRawNodeOrigins result).Nodup := by
  classical
  apply sumEnumerations_nodup
  · exact
      (attach_nodup_of_nodup _
        ((Data.Finite.allFin_nodup _).filter _)).map _ (by
          intro left right different equality
          apply different
          apply Subtype.ext
          exact congrArg
            (fun origin : { node : source.val.NodeId //
              node ∉ result.applications } => origin.1) equality)
  · apply flatMap_nodup_of_disjoint (Data.Finite.allFin_nodup _)
    · intro occurrence _
      rw [List.nodup_append]
      refine ⟨?_, ?_, by simp⟩
      · exact (Data.Finite.allFin_nodup _).map _ (by simp)
      · exact (Data.Finite.allFin_nodup _).map _ (by simp)
    · intro left _ right _ different first firstMember second secondMember equality
      apply different
      have firstOccurrence : first.1 = left := by
        rcases List.mem_append.mp firstMember with member | member
        · rcases List.mem_map.mp member with ⟨node, _, rfl⟩
          rfl
        · rcases List.mem_map.mp member with ⟨request, _, rfl⟩
          rfl
      have secondOccurrence : second.1 = right := by
        rcases List.mem_append.mp secondMember with member | member
        · rcases List.mem_map.mp member with ⟨node, _, rfl⟩
          rfl
        · rcases List.mem_map.mp member with ⟨request, _, rfl⟩
          rfl
      exact firstOccurrence.symm.trans
        ((congrArg Sigma.fst equality).trans secondOccurrence)

theorem relationJoinRawWireOrigins_nodup
    (result : RelationJoinResult source dying content parameters) :
    (relationJoinRawWireOrigins result).Nodup := by
  classical
  apply sumEnumerations_nodup
  · exact
      (attach_nodup_of_nodup _
        ((Data.Finite.allFin_nodup _).filter _)).map _ (by
          intro left right different equality
          apply different
          apply Subtype.ext
          exact congrArg
            (fun origin : { wire : source.val.WireId // wire ≠ dying } =>
              origin.1) equality)
  · apply flatMap_nodup_of_disjoint (Data.Finite.allFin_nodup _)
    · intro occurrence _
      exact (attach_nodup_of_nodup _
        ((Data.Finite.allFin_nodup _).filter _)).map _ (by
          intro left right different equality
          apply different
          apply Subtype.ext
          exact congrArg (fun origin => origin.2.1) equality)
    · intro left _ right _ different first firstMember second secondMember equality
      apply different
      have firstOccurrence : first.1 = left := by
        rcases List.mem_map.mp firstMember with ⟨wire, _, rfl⟩
        rfl
      have secondOccurrence : second.1 = right := by
        rcases List.mem_map.mp secondMember with ⟨wire, _, rfl⟩
        rfl
      exact firstOccurrence.symm.trans
        ((congrArg Sigma.fst equality).trans secondOccurrence)

theorem relationJoinRawRegionOrigins_complete
    (result : RelationJoinResult source dying content parameters)
    (origin : RelationJoinRawRegionOrigin result) :
    origin ∈ relationJoinRawRegionOrigins result := by
  classical
  rcases origin with region | ⟨occurrence, region, nonroot⟩
  · simp [relationJoinRawRegionOrigins, ConcreteDiagram.regionsList,
      Data.Finite.mem_allFin]
  · simp [relationJoinRawRegionOrigins,
      ConcreteSpliceAttachment.fragmentRegions,
      ConcreteDiagram.regionsList, Data.Finite.mem_allFin, nonroot]

theorem relationJoinRawNodeOrigins_complete
    (result : RelationJoinResult source dying content parameters)
    (origin : RelationJoinRawNodeOrigin result) :
    origin ∈ relationJoinRawNodeOrigins result := by
  classical
  rcases origin with ⟨node, survives⟩ | ⟨occurrence, node | request⟩
  · simp [relationJoinRawNodeOrigins, ConcreteDiagram.nodesList,
      Data.Finite.mem_allFin, survives]
  · apply List.mem_append.mpr
    right
    apply List.mem_map.mpr
    refine ⟨⟨occurrence, Sum.inl node⟩, ?_, rfl⟩
    apply List.mem_flatMap.mpr
    refine ⟨occurrence, Data.Finite.mem_allFin occurrence, ?_⟩
    apply List.mem_append.mpr
    left
    exact List.mem_map.mpr
      ⟨node, Data.Finite.mem_allFin node, rfl⟩
  · apply List.mem_append.mpr
    right
    apply List.mem_map.mpr
    refine ⟨⟨occurrence, Sum.inr request⟩, ?_, rfl⟩
    apply List.mem_flatMap.mpr
    refine ⟨occurrence, Data.Finite.mem_allFin occurrence, ?_⟩
    apply List.mem_append.mpr
    right
    exact List.mem_map.mpr
      ⟨request, Data.Finite.mem_allFin request, rfl⟩

theorem relationJoinRawWireOrigins_complete
    (result : RelationJoinResult source dying content parameters)
    (origin : RelationJoinRawWireOrigin result) :
    origin ∈ relationJoinRawWireOrigins result := by
  classical
  rcases origin with ⟨wire, survives⟩ | ⟨occurrence, wire, internal⟩
  · simp [relationJoinRawWireOrigins, ConcreteDiagram.wiresList,
      Data.Finite.mem_allFin, survives]
  · simp [relationJoinRawWireOrigins,
      ConcreteSpliceAttachment.fragmentInternalWires,
      ConcreteDiagram.wiresList, Data.Finite.mem_allFin, internal]

private def relationJoinRawRegionFreshCount
    (steps : List (RelationJoinStep source dying content)) : Nat :=
  (steps.map fun step => step.attachment.fragmentRegions.length).sum

private def relationJoinRawNodeFreshCount
    (steps : List (RelationJoinStep source dying content)) : Nat :=
  (steps.map fun step =>
    content.val.diagram.nodeCount + step.attachment.identityRequests.length).sum

private def relationJoinRawWireFreshCount
    (steps : List (RelationJoinStep source dying content)) : Nat :=
  (steps.map fun step => step.attachment.fragmentInternalWires.length).sum

private theorem map_get_allFin (values : List α) :
    (Data.Finite.allFin values.length).map values.get = values := by
  rw [Data.Finite.allFin_eq_finRange]
  unfold List.finRange
  rw [List.map_ofFn]
  simpa only [Function.comp_apply, List.get_eq_getElem] using
    (List.ofFn_getElem (xs := values))

private theorem sum_map_get_allFin (values : List α) (measure : α → Nat) :
    ((Data.Finite.allFin values.length).map
      (fun index => measure (values.get index))).sum =
        (values.map measure).sum := by
  have mapped := congrArg (List.map measure) (map_get_allFin values)
  have summed := congrArg List.sum mapped
  simpa only [List.map_map, Function.comp_apply] using summed

private theorem sum_map_getNat_allFin (values : List α) (measure : α → Nat) :
    ((Data.Finite.allFin values.length).map
      (fun index => measure values[index.1])).sum =
        (values.map measure).sum := by
  simpa only [List.get_eq_getElem] using sum_map_get_allFin values measure

theorem relationJoinSemanticTrace_regionCount_exact
    {args : List Sig}
    {steps : List (RelationJoinStep source dying content)}
    {final : CheckedDiagram definitions}
    {regionImage : source.val.RegionId → final.val.RegionId}
    {nodeImage : source.val.NodeId → Option final.val.NodeId}
    {wireImage : source.val.WireId → final.val.WireId}
    {finalDying : final.val.WireId}
    {finalScope : final.val.RegionId}
    (trace : RelationJoinSemanticTrace source dying content parameters args
      steps final regionImage nodeImage wireImage finalDying finalScope) :
    final.val.regionCount =
      source.val.regionCount + relationJoinRawRegionFreshCount steps := by
  induction trace with
  | nil => simp [relationJoinRawRegionFreshCount]
  | snoc trace step priorExact _ _ _ _ _ _ _ induction =>
      subst priorExact
      have stepCount := step.checked_regionCount
      simp [relationJoinRawRegionFreshCount] at induction ⊢
      omega

theorem relationJoinSemanticTrace_nodeCount_exact
    {args : List Sig}
    {steps : List (RelationJoinStep source dying content)}
    {final : CheckedDiagram definitions}
    {regionImage : source.val.RegionId → final.val.RegionId}
    {nodeImage : source.val.NodeId → Option final.val.NodeId}
    {wireImage : source.val.WireId → final.val.WireId}
    {finalDying : final.val.WireId}
    {finalScope : final.val.RegionId}
    (trace : RelationJoinSemanticTrace source dying content parameters args
      steps final regionImage nodeImage wireImage finalDying finalScope) :
    final.val.nodeCount + steps.length =
      source.val.nodeCount + relationJoinRawNodeFreshCount steps := by
  induction trace with
  | nil => simp [relationJoinRawNodeFreshCount]
  | snoc trace step priorExact _ _ _ _ _ _ _ induction =>
      subst priorExact
      have stepCount := step.checked_nodeCount_add_one
      simp [relationJoinRawNodeFreshCount] at induction ⊢
      omega

theorem relationJoinSemanticTrace_wireCount_exact
    {args : List Sig}
    {steps : List (RelationJoinStep source dying content)}
    {final : CheckedDiagram definitions}
    {regionImage : source.val.RegionId → final.val.RegionId}
    {nodeImage : source.val.NodeId → Option final.val.NodeId}
    {wireImage : source.val.WireId → final.val.WireId}
    {finalDying : final.val.WireId}
    {finalScope : final.val.RegionId}
    (trace : RelationJoinSemanticTrace source dying content parameters args
      steps final regionImage nodeImage wireImage finalDying finalScope) :
    final.val.wireCount =
      source.val.wireCount + relationJoinRawWireFreshCount steps := by
  induction trace with
  | nil => simp [relationJoinRawWireFreshCount]
  | snoc trace step priorExact _ _ _ _ _ _ _ induction =>
      subst priorExact
      have stepCount := step.checked_wireCount
      simp [relationJoinRawWireFreshCount] at induction ⊢
      omega

theorem relationJoinRawRegionOrigins_length
    (result : RelationJoinResult source dying content parameters) :
    result.plainFinal.val.regionCount =
      (relationJoinRawRegionOrigins result).length := by
  rw [result.plainFinal_regionCount]
  rw [relationJoinSemanticTrace_regionCount_exact result.semantic_trace]
  simp [relationJoinRawRegionOrigins, relationJoinRawRegionFreshCount,
    ConcreteDiagram.regionsList]
  rw [sum_map_getNat_allFin result.steps
    (fun step => step.attachment.fragmentRegions.length)]
  simp [Data.Finite.allFin_eq_finRange]

theorem relationJoinRawNodeOrigins_length
    (result : RelationJoinResult source dying content parameters) :
    result.plainFinal.val.nodeCount =
      (relationJoinRawNodeOrigins result).length := by
  have traceCount :=
    relationJoinSemanticTrace_nodeCount_exact result.semantic_trace
  have applicationNodup : result.applications.Nodup := by
    rw [result.applications_storage_order]
    exact (Data.Finite.allFin_nodup _).filter _
  have retainedCount :=
    Data.Finite.filter_not_mem_length_add_removed_length
      result.applications applicationNodup
  have stepsLength : result.steps.length = result.applications.length := by
    have exact := congrArg List.length result.steps_application_order
    simpa using exact
  rw [result.plainFinal_nodeCount]
  simp [decide_not, Data.Finite.allFin_eq_finRange] at retainedCount
  simp [relationJoinRawNodeFreshCount] at traceCount
  simp [relationJoinRawNodeOrigins,
    ConcreteDiagram.nodesList] at ⊢
  rw [sum_map_getNat_allFin result.steps
    (fun step =>
      (Data.Finite.allFin content.val.diagram.nodeCount).length +
        (Data.Finite.allFin step.attachment.identityRequests.length).length)]
  simp [Data.Finite.allFin_eq_finRange] at ⊢
  change result.boundFinal.val.nodeCount =
    (List.filter (fun value => !decide (value ∈ result.applications))
      (List.finRange source.val.nodeCount)).length +
        (result.steps.map fun step =>
          content.val.diagram.nodeCount +
            step.attachment.identityRequests.length).sum
  have retainedCount' :
      (List.filter (fun value => !decide (value ∈ result.applications))
        (List.finRange source.val.nodeCount)).length +
          result.applications.length = source.val.nodeCount := by
    simpa only using retainedCount
  clear retainedCount
  omega

theorem relationJoinRawWireOrigins_length
    (result : RelationJoinResult source dying content parameters) :
    result.plainFinal.val.wireCount =
      (relationJoinRawWireOrigins result).length := by
  have traceCount :=
    relationJoinSemanticTrace_wireCount_exact result.semantic_trace
  have retainedCount :=
    Data.Finite.filter_not_mem_length_add_removed_length
      [dying] (by simp)
  have finalCount := result.plainFinal_wireCount_add_one
  simp [decide_not, Data.Finite.allFin_eq_finRange] at retainedCount
  simp [relationJoinRawWireFreshCount] at traceCount
  simp [relationJoinRawWireOrigins,
    ConcreteDiagram.wiresList] at ⊢
  rw [sum_map_getNat_allFin result.steps
    (fun step => step.attachment.fragmentInternalWires.length)]
  simp [Data.Finite.allFin_eq_finRange] at ⊢
  change result.plainFinal.val.wireCount =
    (List.filter (fun value => !decide (value = dying))
      (List.finRange source.val.wireCount)).length +
        (result.steps.map fun step =>
          step.attachment.fragmentInternalWires.length).sum
  have retainedCount' :
      (List.filter (fun value => !decide (value = dying))
        (List.finRange source.val.wireCount)).length + 1 =
          source.val.wireCount := by
    simpa only using retainedCount
  clear retainedCount
  omega

/-- Executable equivalence from dense positions to a complete nodup
enumeration.  Proof fields justify lookup but do not select runtime data. -/
private def finiteEquivOfEnumeration [DecidableEq α]
    (values : List α)
    (nodup : values.Nodup)
    (complete : ∀ value, value ∈ values) :
    Data.Finite.FiniteEquiv (Fin values.length) α where
  toFun := values.get
  invFun := fun value =>
    (Data.Finite.indexOf? values value).get (by
      rw [Data.Finite.indexOf?_isSome_iff]
      exact complete value)
  left_inv := by
    intro position
    let foundSome :
        (Data.Finite.indexOf? values (values.get position)).isSome = true :=
      Data.Finite.indexOf?_isSome_iff.mpr (List.get_mem values position)
    exact Option.get_of_eq_some foundSome
      (Data.Finite.indexOf?_get_eq_some_of_nodup nodup position)
  right_inv := by
    intro value
    let found := Data.Finite.indexOf? values value
    have foundSome : found.isSome = true := by
      rw [Data.Finite.indexOf?_isSome_iff]
      exact complete value
    obtain ⟨position, positionExact⟩ :=
      Option.isSome_iff_exists.mp foundSome
    rw [Option.get_of_eq_some foundSome positionExact]
    exact Data.Finite.indexOf?_sound positionExact

/-- Constructive, allocation-neutral classifiers for every final raw carrier.
The inverse maps recover the dense raw identifier assigned to each origin. -/
structure RelationJoinRawOriginAtlas
    (result : RelationJoinResult source dying content parameters) where
  regionEquiv : Data.Finite.FiniteEquiv result.plainFinal.val.RegionId
    (RelationJoinRawRegionOrigin result)
  nodeEquiv : Data.Finite.FiniteEquiv result.plainFinal.val.NodeId
    (RelationJoinRawNodeOrigin result)
  wireEquiv : Data.Finite.FiniteEquiv result.plainFinal.val.WireId
    (RelationJoinRawWireOrigin result)

namespace RelationJoinRawOriginAtlas

/-- Compute all three raw-origin classifiers from the semantic receipt. -/
def ofResult
    (result : RelationJoinResult source dying content parameters) :
    RelationJoinRawOriginAtlas result where
  regionEquiv :=
    (Data.Finite.FiniteEquiv.finCast
      (relationJoinRawRegionOrigins_length result)).trans
        (finiteEquivOfEnumeration
          (relationJoinRawRegionOrigins result)
          (relationJoinRawRegionOrigins_nodup result)
          (relationJoinRawRegionOrigins_complete result))
  nodeEquiv :=
    (Data.Finite.FiniteEquiv.finCast
      (relationJoinRawNodeOrigins_length result)).trans
        (finiteEquivOfEnumeration
          (relationJoinRawNodeOrigins result)
          (relationJoinRawNodeOrigins_nodup result)
          (relationJoinRawNodeOrigins_complete result))
  wireEquiv :=
    (Data.Finite.FiniteEquiv.finCast
      (relationJoinRawWireOrigins_length result)).trans
        (finiteEquivOfEnumeration
          (relationJoinRawWireOrigins result)
          (relationJoinRawWireOrigins_nodup result)
          (relationJoinRawWireOrigins_complete result))

/-- Classify a raw final region by allocation-neutral origin. -/
def regionOrigin (atlas : RelationJoinRawOriginAtlas result)
    (region : result.plainFinal.val.RegionId) :
    RelationJoinRawRegionOrigin result :=
  atlas.regionEquiv region

/-- Classify a raw final node by allocation-neutral origin. -/
def nodeOrigin (atlas : RelationJoinRawOriginAtlas result)
    (node : result.plainFinal.val.NodeId) :
    RelationJoinRawNodeOrigin result :=
  atlas.nodeEquiv node

/-- Classify a raw final wire by allocation-neutral origin. -/
def wireOrigin (atlas : RelationJoinRawOriginAtlas result)
    (wire : result.plainFinal.val.WireId) :
    RelationJoinRawWireOrigin result :=
  atlas.wireEquiv wire

end RelationJoinRawOriginAtlas

end Origins

end MonolithicWireQuantifier

end VisualProof
