import VisualProof.Diagram.Scope.Context
import VisualProof.Rule.Relation

namespace VisualProof.Rule

open Theory
open Diagram

namespace Presentation

/-- One positive-arity identity node in a presentation configuration.  The
stored number is one less than the actual arity, so nullary points cannot
enter this rule's operation data. -/
structure Node (wires : List Sig) (signature : Sig) where
  extraArity : Nat
  ports : Fin (extraArity + 1) → Var wires signature

namespace Node

def item (node : Node wires signature) : Item wires :=
  .identity signature (node.extraArity + 1) node.ports

def portList (node : Node wires signature) : List (Var wires signature) :=
  List.ofFn node.ports

def indices (node : Node wires signature) : List Nat :=
  List.ofFn fun index => (node.ports index).index.val

end Node

/-- Flat replacement data for the positive-arity identity nodes of one
signature at one region.  This is not a diagram representation or a graph;
the recursive `Region`/`Item` syntax remains the sole syntax. -/
abbrev Configuration (wires : List Sig) (signature : Sig) :=
  List (Node wires signature)

namespace Configuration

def items : Configuration wires signature → ItemSeq wires
  | [] => .nil
  | node :: tail => .cons node.item (Configuration.items tail)

def indices : Configuration wires signature → List Nat
  | [] => []
  | node :: tail =>
      node.indices ++ Configuration.indices tail

def ports : Configuration wires signature → List (Var wires signature)
  | [] => []
  | node :: tail => node.portList ++ Configuration.ports tail

def Adjacent (configuration : Configuration wires signature)
    (left right : Var wires signature) : Prop :=
  ∃ node ∈ configuration,
    left ∈ node.portList ∧ right ∈ node.portList

/-- The finite equivalence relation generated by co-membership in one
identity node. Its structural decision procedure follows the configuration
recursion and is used to check presentation applicability. -/
inductive Generated (configuration : Configuration wires signature) :
    Var wires signature → Var wires signature → Prop
  | refl (wire) : Generated configuration wire wire
  | adjacent (evidence : configuration.Adjacent left right) :
      Generated configuration left right
  | symm (evidence : Generated configuration left right) :
      Generated configuration right left
  | trans (first : Generated configuration left middle)
      (second : Generated configuration middle right) :
      Generated configuration left right

theorem Generated.of_tail
    (generated : Generated tail left right) :
    Generated (node :: tail) left right := by
  induction generated with
  | refl wire => exact .refl wire
  | adjacent evidence =>
      exact .adjacent ⟨evidence.choose, List.mem_cons_of_mem _ evidence.choose_spec.1,
        evidence.choose_spec.2⟩
  | symm evidence induction => exact induction.symm
  | trans first second firstInduction secondInduction =>
      exact firstInduction.trans secondInduction

theorem Generated.head
    (leftMember : left ∈ node.portList)
    (rightMember : right ∈ node.portList) :
    Generated (node :: tail) left right :=
  .adjacent ⟨node, List.mem_cons_self, leftMember, rightMember⟩

theorem Generated.nil_iff :
    Generated ([] : Configuration wires signature) left right ↔ left = right := by
  constructor
  · intro generated
    induction generated with
    | refl wire => rfl
    | adjacent evidence => simp [Adjacent] at evidence
    | symm evidence induction => exact induction.symm
    | trans first second firstInduction secondInduction =>
        exact firstInduction.trans secondInduction
  · rintro rfl
    exact .refl left

theorem Generated.cons_iff :
    Generated (node :: tail) left right ↔
      Generated tail left right ∨
        ∃ first ∈ node.portList, ∃ second ∈ node.portList,
          Generated tail left first ∧ Generated tail second right := by
  let ConnectedAfter := fun left right =>
    Generated tail left right ∨
      ∃ first ∈ node.portList, ∃ second ∈ node.portList,
        Generated tail left first ∧ Generated tail second right
  have reflexive : ∀ wire, ConnectedAfter wire wire :=
    fun wire => Or.inl (.refl wire)
  have symmetric : ∀ {left right}, ConnectedAfter left right →
      ConnectedAfter right left := by
    intro left right connected
    rcases connected with generated | ⟨first, firstMember, second,
        secondMember, leftFirst, secondRight⟩
    · exact Or.inl generated.symm
    · exact Or.inr ⟨second, secondMember, first, firstMember,
        secondRight.symm, leftFirst.symm⟩
  have transitive : ∀ {left middle right},
      ConnectedAfter left middle → ConnectedAfter middle right →
        ConnectedAfter left right := by
    intro left middle right leftMiddle middleRight
    rcases leftMiddle with leftMiddle | ⟨first, firstMember, second,
        secondMember, leftFirst, secondMiddle⟩
    · rcases middleRight with middleRight | ⟨first, firstMember, second,
          secondMember, middleFirst, secondRight⟩
      · exact Or.inl (leftMiddle.trans middleRight)
      · exact Or.inr ⟨first, firstMember, second, secondMember,
          leftMiddle.trans middleFirst, secondRight⟩
    · rcases middleRight with middleRight | ⟨third, thirdMember, fourth,
          fourthMember, middleThird, fourthRight⟩
      · exact Or.inr ⟨first, firstMember, second, secondMember,
          leftFirst, secondMiddle.trans middleRight⟩
      · exact Or.inr ⟨first, firstMember, fourth, fourthMember,
          leftFirst, fourthRight⟩
  constructor
  · intro generated
    induction generated with
    | refl wire => exact reflexive wire
    | adjacent evidence =>
        rcases evidence with ⟨selected, selectedMember, leftMember,
          rightMember⟩
        rcases List.mem_cons.mp selectedMember with rfl | tailMember
        · exact Or.inr ⟨_, leftMember, _, rightMember,
            .refl _, .refl _⟩
        · exact Or.inl (.adjacent
            ⟨selected, tailMember, leftMember, rightMember⟩)
    | symm evidence induction => exact symmetric induction
    | trans first second firstInduction secondInduction =>
        exact transitive firstInduction secondInduction
  · rintro (generated | ⟨first, firstMember, second, secondMember,
      leftFirst, secondRight⟩)
    · exact generated.of_tail
    · exact (leftFirst.of_tail.trans (Generated.head firstMember secondMember)).trans
        secondRight.of_tail

def Generated.decidable : (configuration : Configuration wires signature) →
    (left right : Var wires signature) →
      Decidable (Generated configuration left right)
  | [], left, right =>
      decidable_of_iff (left = right) Generated.nil_iff.symm
  | node :: tail, left, right =>
      letI : ∀ left right, Decidable (Generated tail left right) :=
        Generated.decidable tail
      decidable_of_iff
        (Generated tail left right ∨
          ∃ first ∈ node.portList, ∃ second ∈ node.portList,
            Generated tail left first ∧ Generated tail second right)
        Generated.cons_iff.symm

instance (configuration : Configuration wires signature)
    (left right : Var wires signature) :
    Decidable (Generated configuration left right) :=
  Generated.decidable configuration left right

def SameSupport (source target : Configuration wires signature) : Prop :=
  ∀ wireIndex, wireIndex ∈ source.indices ↔ wireIndex ∈ target.indices

def SameRelation (source target : Configuration wires signature) : Prop :=
  ∀ left right,
    source.Generated left right ↔ target.Generated left right

theorem mem_ports_of_node
    {configuration : Configuration wires signature}
    {node : Node wires signature} {wire : Var wires signature}
    (nodeMember : node ∈ configuration)
    (portMember : wire ∈ node.portList) :
    wire ∈ configuration.ports := by
  induction configuration with
  | nil => simp at nodeMember
  | cons head tail induction =>
      rcases List.mem_cons.mp nodeMember with rfl | tailMember
      · exact List.mem_append_left _ portMember
      · exact List.mem_append_right _ (induction tailMember)

theorem Generated.eq_or_mem_ports
    {configuration : Configuration wires signature}
    {left right : Var wires signature}
    (generated : configuration.Generated left right) :
    left = right ∨
      (left ∈ configuration.ports ∧ right ∈ configuration.ports) := by
  induction generated with
  | refl wire => exact Or.inl rfl
  | adjacent evidence =>
      exact Or.inr
        ⟨mem_ports_of_node evidence.choose_spec.1 evidence.choose_spec.2.1,
          mem_ports_of_node evidence.choose_spec.1 evidence.choose_spec.2.2⟩
  | symm evidence induction =>
      exact induction.elim (fun equal => Or.inl equal.symm)
        (fun supported => Or.inr ⟨supported.2, supported.1⟩)
  | trans first second firstInduction secondInduction =>
      rcases firstInduction with firstEqual | firstSupported
      · rcases firstEqual with rfl
        exact secondInduction
      · rcases secondInduction with secondEqual | secondSupported
        · rcases secondEqual with rfl
          exact Or.inr firstSupported
        · exact Or.inr ⟨firstSupported.1, secondSupported.2⟩

theorem Generated.mem_ports_of_ne
    {configuration : Configuration wires signature}
    {left right : Var wires signature}
    (generated : configuration.Generated left right)
    (different : left ≠ right) :
    left ∈ configuration.ports ∧ right ∈ configuration.ports := by
  rcases generated.eq_or_mem_ports with equal | supported
  · exact False.elim (different equal)
  · exact supported

private def Every (predicate : α → Prop) : List α → Prop
  | [] => True
  | head :: tail => predicate head ∧ Every predicate tail

private def Every.decidable {predicate : α → Prop}
    [∀ value, Decidable (predicate value)] :
    (values : List α) → Decidable (Every predicate values)
  | [] => isTrue trivial
  | head :: tail =>
      match inferInstanceAs (Decidable (predicate head)),
          Every.decidable tail with
      | isTrue headEvidence, isTrue tailEvidence =>
          isTrue ⟨headEvidence, tailEvidence⟩
      | isFalse headRefutation, _ =>
          isFalse (fun evidence => headRefutation evidence.1)
      | _, isFalse tailRefutation =>
          isFalse (fun evidence => tailRefutation evidence.2)

private instance {predicate : α → Prop}
    [∀ value, Decidable (predicate value)] (values : List α) :
    Decidable (Every predicate values) := Every.decidable values

private theorem every_iff_forall_mem
    {predicate : α → Prop} {values : List α} :
    Every predicate values ↔ ∀ value ∈ values, predicate value := by
  induction values with
  | nil => simp [Every]
  | cons head tail induction =>
      simp only [Every, List.mem_cons, forall_eq_or_imp, induction]

private def RelationsAgree
    (source target : Configuration wires signature) : Prop :=
  let candidates := source.ports ++ target.ports
  Every (fun left => Every (fun right =>
    source.Generated left right ↔ target.Generated left right) candidates)
    candidates

private def generatedIffDecidable
    (source target : Configuration wires signature)
    (left right : Var wires signature) :
    Decidable (source.Generated left right ↔
      target.Generated left right) := inferInstance

private def relationsAgreeDecidable
    (source target : Configuration wires signature) :
    Decidable (RelationsAgree source target) := by
  let candidates := source.ports ++ target.ports
  change Decidable (Every (fun left => Every (fun right =>
    source.Generated left right ↔ target.Generated left right) candidates)
    candidates)
  exact @Every.decidable _ _
    (fun left => @Every.decidable _ _
      (fun right => generatedIffDecidable source target left right) candidates)
    candidates

private theorem relationsAgree_iff
    (source target : Configuration wires signature) :
    RelationsAgree source target ↔
      ∀ left ∈ source.ports ++ target.ports,
        ∀ right ∈ source.ports ++ target.ports,
          source.Generated left right ↔ target.Generated left right := by
  simp only [RelationsAgree, every_iff_forall_mem]

private theorem sameRelation_iff_relationsAgree
    (source target : Configuration wires signature) :
    source.SameRelation target ↔ RelationsAgree source target := by
  rw [relationsAgree_iff]
  constructor
  · intro sameRelation left _ right _
    exact sameRelation left right
  · intro agrees left right
    by_cases equal : left = right
    · subst right
      exact ⟨fun _ => .refl left, fun _ => .refl left⟩
    · constructor
      · intro generated
        have supported := generated.mem_ports_of_ne equal
        exact (agrees left (List.mem_append_left _ supported.1)
          right (List.mem_append_left _ supported.2)).mp generated
      · intro generated
        have supported := generated.mem_ports_of_ne equal
        exact (agrees left (List.mem_append_right _ supported.1)
          right (List.mem_append_right _ supported.2)).mpr generated

instance (source target : Configuration wires signature) :
    Decidable (source.SameRelation target) := by
  letI : Decidable (RelationsAgree source target) :=
    relationsAgreeDecidable source target
  exact decidable_of_iff (RelationsAgree source target)
    (sameRelation_iff_relationsAgree source target).symm

theorem sameSupport_iff_subset
    (source target : Configuration wires signature) :
    source.SameSupport target ↔
      (∀ wireIndex ∈ source.indices, wireIndex ∈ target.indices) ∧
      (∀ wireIndex ∈ target.indices, wireIndex ∈ source.indices) := by
  constructor
  · intro sameSupport
    exact ⟨fun wireIndex member => (sameSupport wireIndex).mp member,
      fun wireIndex member => (sameSupport wireIndex).mpr member⟩
  · rintro ⟨forward, backward⟩ wireIndex
    exact ⟨forward wireIndex, backward wireIndex⟩

instance (source target : Configuration wires signature) :
    Decidable (source.SameSupport target) :=
  decidable_of_iff
    ((∀ wireIndex ∈ source.indices, wireIndex ∈ target.indices) ∧
      (∀ wireIndex ∈ target.indices, wireIndex ∈ source.indices))
    (sameSupport_iff_subset source target).symm

theorem items_childrenCanonical
    (configuration : Configuration wires signature) :
    configuration.items.ChildrenCanonical := by
  induction configuration with
  | nil => trivial
  | cons node tail induction =>
      exact ⟨True.intro, induction⟩

theorem items_incidencePaths_nonempty_iff
    (configuration : Configuration wires signature)
    (wireIndex itemIndex : Nat) :
    configuration.items.incidencePaths wireIndex itemIndex ≠ [] ↔
      wireIndex ∈ configuration.indices := by
  induction configuration generalizing itemIndex with
  | nil => simp [items, indices, ItemSeq.incidencePaths]
  | cons node tail induction =>
      simp only [items, indices, ItemSeq.incidencePaths, Node.item,
        Item.incidencePaths, List.mem_append, Node.indices]
      constructor
      · intro nonempty
        by_cases nodeMember : wireIndex ∈
            List.ofFn (fun index => (node.ports index).index.val)
        · exact Or.inl nodeMember
        · apply Or.inr
          apply (induction (itemIndex := itemIndex + 1)).mp
          intro tailEmpty
          apply nonempty
          apply (List.append_eq_nil_iff).mpr
          constructor
          · apply (List.replicate_eq_nil_iff []).mpr
            exact (List.count_eq_zero).mpr nodeMember
          · exact tailEmpty
      · rintro (member | member)
        · intro empty
          have replicatedEmpty := (List.append_eq_nil_iff.mp empty).1
          have countZero := (List.replicate_eq_nil_iff []).mp replicatedEmpty
          exact ((List.count_eq_zero.mp countZero) member)
        · have tailNonempty :=
            (induction (itemIndex := itemIndex + 1)).mpr member
          intro empty
          exact tailNonempty (List.append_eq_nil_iff.mp empty).2

end Configuration

/-- Canonical suffix form used by the exact source occurrence.  Arbitrary
physical item placement is covered by the existing `ItemSeqIso` permutation
in the occurrence's source presentation and by target-isomorphism closure. -/
def region (locals : List Sig) (retained : ItemSeq (outer ++ locals))
    (configuration : Configuration (outer ++ locals) signature) :
    Region outer :=
  .mk locals (retained.append configuration.items)

/-- Exact applicability for the computed replacement.  Equal support keeps
every selected wire present on both sides; the local rooted-two field is the
only target-validity condition not inherited structurally from the source. -/
structure Applicability (outer : List Sig)
    (locals : List Sig) (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) signature) : Prop where
  sameSupport : source.SameSupport target
  sameRelation : source.SameRelation target
  targetLocalRooted : ∀ localIndex : Fin locals.length,
    RegionPath.RootedTwo
      ((region locals retained target).incidencePaths
        (outer.length + localIndex.val))

theorem applicability_iff
    (outer : List Sig) (locals : List Sig)
    (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) signature) :
    Applicability outer locals retained source target ↔
      source.SameSupport target ∧ source.SameRelation target ∧
        ∀ localIndex : Fin locals.length,
          RegionPath.RootedTwo
            ((region locals retained target).incidencePaths
              (outer.length + localIndex.val)) := by
  constructor
  · intro applicability
    exact ⟨applicability.sameSupport, applicability.sameRelation,
      applicability.targetLocalRooted⟩
  · rintro ⟨sameSupport, sameRelation, targetLocalRooted⟩
    exact ⟨sameSupport, sameRelation, targetLocalRooted⟩

instance (outer : List Sig) (locals : List Sig)
    (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) signature) :
    Decidable (Applicability outer locals retained source target) :=
  decidable_of_iff
    (source.SameSupport target ∧ source.SameRelation target ∧
      ∀ localIndex : Fin locals.length,
        RegionPath.RootedTwo
          ((region locals retained target).incidencePaths
            (outer.length + localIndex.val)))
    (applicability_iff outer locals retained source target).symm

namespace Applicability

theorem symm
    {outer : List Sig}
    {locals : List Sig}
    {retained : ItemSeq (outer ++ locals)}
    {signature : Sig}
    {source target : Configuration (outer ++ locals) signature}
    (applicability : Applicability outer locals retained source target)
    (sourceLocalRooted : ∀ localIndex : Fin locals.length,
      RegionPath.RootedTwo
        ((region locals retained source).incidencePaths
          (outer.length + localIndex.val))) :
    Applicability outer locals retained target source := by
  exact {
    sameSupport := fun wireIndex =>
      (applicability.sameSupport wireIndex).symm
    sameRelation := fun left right =>
      (applicability.sameRelation left right).symm
    targetLocalRooted := sourceLocalRooted
  }

end Applicability

theorem incidencePaths_nonempty_iff
    (locals : List Sig) (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) signature)
    (sameSupport : source.SameSupport target)
    (wireIndex : Nat) :
    (region locals retained source).incidencePaths wireIndex ≠ [] ↔
      (region locals retained target).incidencePaths wireIndex ≠ [] := by
  simp only [region, Region.incidencePaths, ItemSeq.incidencePaths_append]
  let retainedPaths := retained.incidencePaths wireIndex 0
  let sourcePaths := source.items.incidencePaths wireIndex retained.length
  let targetPaths := target.items.incidencePaths wireIndex retained.length
  have suffixIff : sourcePaths ≠ [] ↔ targetPaths ≠ [] := by
    rw [Configuration.items_incidencePaths_nonempty_iff,
      Configuration.items_incidencePaths_nonempty_iff]
    exact sameSupport wireIndex
  by_cases retainedEmpty : retainedPaths = []
  · simp only [retainedPaths] at retainedEmpty
    simpa only [retainedPaths, sourcePaths, targetPaths, retainedEmpty,
      List.nil_append, Nat.zero_add] using suffixIff
  · constructor <;> intro _ <;>
      exact List.append_ne_nil_of_left_ne_nil retainedEmpty _

theorem targetCanonical
    {outer : List Sig} {locals : List Sig}
    {retained : ItemSeq (outer ++ locals)} {signature : Sig}
    {source target : Configuration (outer ++ locals) signature}
    (occurrence : Occurrence (region locals retained source) host)
    (applicability : Applicability outer locals retained source target) :
    (region locals retained target).Canonical := by
  have sourceCanonical := occurrence.context.holeCanonical _
    occurrence.sourceCanonical
  refine ⟨applicability.targetLocalRooted, ?_⟩
  have sourceChildren := sourceCanonical.2
  simp only [region, Region.Canonical] at sourceCanonical ⊢
  rw [ItemSeq.childrenCanonical_append] at sourceChildren ⊢
  exact ⟨sourceChildren.1, Configuration.items_childrenCanonical target⟩

theorem replacementValidity
    {outer : List Sig} {locals : List Sig}
    {retained : ItemSeq (outer ++ locals)} {signature : Sig}
    {source target : Configuration (outer ++ locals) signature}
    (occurrence : Occurrence (region locals retained source) host)
    (applicability : Applicability outer locals retained source target) :
    (occurrence.context.fill (region locals retained target)).Canonical ∧
      OpenDiagram.ExternalTwoEnded occurrence.interface.boundaryWire
        (occurrence.context.fill (region locals retained target)) := by
  have localTarget := targetCanonical occurrence applicability
  have sameNonempty := incidencePaths_nonempty_iff locals retained source target
    applicability.sameSupport
  have replaced := occurrence.context.replaceCanonical
    (region locals retained source) (region locals retained target)
    occurrence.sourceCanonical localTarget (fun wire =>
      sameNonempty wire.index.val)
  let sourceEndpoint := occurrence.interface.withBody
    (occurrence.context.fill (region locals retained source))
      occurrence.sourceCanonical occurrence.sourceExternalTwoEnded
  exact ⟨replaced.1,
    sourceEndpoint.externalTwoEnded_of_nonempty_iff
      (occurrence.context.fill (region locals retained target)) replaced.2⟩

/-- One local presentation replacement, with the exact retained regional
syntax, source configuration, replacement data, and applicability evidence. -/
inductive Local : LocalRule
  | replace (locals : List Sig)
      (retained : ItemSeq (outer ++ locals))
      (signature : Sig)
      (source target : Configuration (outer ++ locals) signature)
      (applicability : Applicability outer locals retained source target) :
      Local (region locals retained source) (region locals retained target)

private def Configuration.noInternalWire
    (configuration : Configuration wires presentationSignature) :
    ItemSeq.InternalWire configuration.items wireSignature → False := by
  intro wire
  induction configuration with
  | nil => exact nomatch wire
  | cons node tail induction =>
      cases wire with
      | tail nested => exact induction nested

private def mapRetainedInternal
    (source target : Configuration wires presentationSignature)
    (retained : ItemSeq wires)
    (wire : ItemSeq.InternalWire
      (retained.append source.items) wireSignature) :
    ItemSeq.InternalWire (retained.append target.items) wireSignature :=
  match retained with
  | .nil => False.elim (source.noInternalWire wire)
  | .cons head tail =>
      match head with
      | .atom _ _ =>
          match wire with
          | .tail nested =>
              .tail (mapRetainedInternal source target tail nested)
      | .identity _ _ _ =>
          match wire with
          | .tail nested =>
              .tail (mapRetainedInternal source target tail nested)
      | .cut _ =>
          match wire with
          | .headCut nested => .headCut nested
          | .tail nested =>
              .tail (mapRetainedInternal source target tail nested)

private theorem ownerPathFrom_mapRetainedInternal
    (retained : ItemSeq wires)
    (source target : Configuration wires presentationSignature)
    (wire : ItemSeq.InternalWire
      (retained.append source.items) wireSignature)
    (itemIndex : Nat) :
    (mapRetainedInternal source target retained wire).ownerPathFrom itemIndex =
      wire.ownerPathFrom itemIndex := by
  cases retained with
  | nil => exact False.elim (source.noInternalWire wire)
  | cons head tail =>
      cases head with
      | atom atomHead atomPorts =>
          cases wire with
          | tail nested =>
              simp only [mapRetainedInternal,
                ItemSeq.InternalWire.ownerPathFrom]
              exact ownerPathFrom_mapRetainedInternal tail source target nested
                (itemIndex + 1)
      | identity signature arity ports =>
          cases wire with
          | tail nested =>
              simp only [mapRetainedInternal,
                ItemSeq.InternalWire.ownerPathFrom]
              exact ownerPathFrom_mapRetainedInternal tail source target nested
                (itemIndex + 1)
      | cut body =>
          cases wire with
          | headCut nested => rfl
          | tail nested =>
              simp only [mapRetainedInternal,
                ItemSeq.InternalWire.ownerPathFrom]
              exact ownerPathFrom_mapRetainedInternal tail source target nested
                (itemIndex + 1)

private def mapRegionInternal
    (locals : List Sig) (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) presentationSignature) :
    Region.InternalWire (region locals retained source) wireSignature →
      Region.InternalWire (region locals retained target) wireSignature
  | .here wire => .here wire
  | .nested wire => .nested (mapRetainedInternal source target retained wire)

private theorem ownerPath_mapRegionInternal
    (locals : List Sig) (retained : ItemSeq (outer ++ locals))
    (source target : Configuration (outer ++ locals) presentationSignature)
    (wire : Region.InternalWire
      (region locals retained source) wireSignature) :
    (mapRegionInternal locals retained source target wire).ownerPath =
      wire.ownerPath := by
  cases wire with
  | here wire => rfl
  | nested wire =>
      exact ownerPathFrom_mapRetainedInternal retained source target wire 0

theorem Local.existsPresentedWire_scopePath
    {before after : Region wires} (step : Local before after)
    (occurrence : Occurrence before source)
    (targetCanonical : (occurrence.context.fill after).Canonical)
    (targetExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      occurrence.interface.boundaryWire (occurrence.context.fill after))
    {signature}
    (wire : OpenDiagram.Wire
      (occurrence.interface.withBody
        (occurrence.context.fill before) occurrence.sourceCanonical
          occurrence.sourceExternalTwoEnded) signature) :
    ∃ targetWire : OpenDiagram.Wire
        (occurrence.interface.withBody
          (occurrence.context.fill after) targetCanonical
            targetExternalTwoEnded) signature,
      (occurrence.interface.withBody
          (occurrence.context.fill after) targetCanonical
            targetExternalTwoEnded).scopePath targetWire =
        (occurrence.interface.withBody
          (occurrence.context.fill before) occurrence.sourceCanonical
            occurrence.sourceExternalTwoEnded).scopePath wire := by
  cases step with
  | replace locals retained presentationSignature sourceConfiguration
      targetConfiguration applicability =>
      cases wire with
      | external externalWire =>
          refine ⟨.external externalWire, ?_⟩
          rw [OpenDiagram.scopePath_external, OpenDiagram.scopePath_external]
      | internal internalWire =>
          let holeMap : ∀ {wireSignature},
              Region.InternalWire
                  (region locals retained sourceConfiguration) wireSignature →
                Region.InternalWire
                  (region locals retained targetConfiguration) wireSignature :=
            mapRegionInternal locals retained sourceConfiguration
              targetConfiguration
          let targetWire := occurrence.context.mapInternalWire holeMap internalWire
          refine ⟨.internal targetWire, ?_⟩
          rw [OpenDiagram.scopePath_internal, OpenDiagram.scopePath_internal]
          exact occurrence.context.ownerPath_mapInternalWire holeMap
            (fun wire => ownerPath_mapRegionInternal locals retained
              sourceConfiguration targetConfiguration wire) internalWire

theorem Local.existsSourceWire_scopePath
    {before after : Region wires} (step : Local before after)
    (occurrence : Occurrence before source)
    (targetCanonical : (occurrence.context.fill after).Canonical)
    (targetExternalTwoEnded : OpenDiagram.ExternalTwoEnded
      occurrence.interface.boundaryWire (occurrence.context.fill after))
    {signature}
    (wire : OpenDiagram.Wire
      (occurrence.interface.withBody
        (occurrence.context.fill after) targetCanonical
          targetExternalTwoEnded) signature) :
    ∃ sourceWire : OpenDiagram.Wire
        (occurrence.interface.withBody
          (occurrence.context.fill before) occurrence.sourceCanonical
            occurrence.sourceExternalTwoEnded) signature,
      (occurrence.interface.withBody
          (occurrence.context.fill before) occurrence.sourceCanonical
            occurrence.sourceExternalTwoEnded).scopePath sourceWire =
        (occurrence.interface.withBody
          (occurrence.context.fill after) targetCanonical
            targetExternalTwoEnded).scopePath wire := by
  cases step with
  | replace locals retained presentationSignature sourceConfiguration
      targetConfiguration applicability =>
      cases wire with
      | external externalWire =>
          refine ⟨.external externalWire, ?_⟩
          rw [OpenDiagram.scopePath_external, OpenDiagram.scopePath_external]
      | internal internalWire =>
          let holeMap : ∀ {wireSignature},
              Region.InternalWire
                  (region locals retained targetConfiguration) wireSignature →
                Region.InternalWire
                  (region locals retained sourceConfiguration) wireSignature :=
            mapRegionInternal locals retained targetConfiguration
              sourceConfiguration
          let sourceWire := occurrence.context.mapInternalWire holeMap internalWire
          refine ⟨.internal sourceWire, ?_⟩
          rw [OpenDiagram.scopePath_internal, OpenDiagram.scopePath_internal]
          exact occurrence.context.ownerPath_mapInternalWire holeMap
            (fun wire => ownerPath_mapRegionInternal locals retained
              targetConfiguration sourceConfiguration wire) internalWire

end Presentation

def Presentation : Rule :=
  Contextual (symmetric Presentation.Local)

theorem Presentation.iso
    (sourceIso : OpenDiagramIso source source')
    (step : Presentation source target)
    (targetIso : OpenDiagramIso target target') :
    Presentation source' target' :=
  Contextual.iso sourceIso step targetIso

theorem Presentation.respectsTargetIso
    (step : Presentation source target)
    (isomorphic : OpenDiagram.Isomorphic target target') :
    Presentation source target' := by
  rcases isomorphic with ⟨targetIso⟩
  exact Presentation.iso (OpenDiagramIso.refl source) step targetIso

theorem Presentation.backward_respectsTargetIso
    (step : Presentation target source)
    (isomorphic : OpenDiagram.Isomorphic target target') :
    Presentation target' source := by
  rcases isomorphic with ⟨targetIso⟩
  exact Presentation.iso targetIso step (OpenDiagramIso.refl source)

theorem Presentation.symm
    (step : Presentation source target) : Presentation target source := by
  rcases step with ⟨wires, before, after, occurrence, targetCanonical,
    targetExternalTwoEnded, targetIso, localEvidence⟩
  let reverseOccurrence : Occurrence after target := {
    interface := occurrence.interface
    context := occurrence.context
    sourceCanonical := targetCanonical
    sourceExternalTwoEnded := targetExternalTwoEnded
    host_iso := targetIso
  }
  refine ⟨wires, after, before, reverseOccurrence,
    occurrence.sourceCanonical, occurrence.sourceExternalTwoEnded,
    occurrence.host_iso, ?_⟩
  cases polarity : occurrence.context.polarity <;>
    simp only [polarity, atPolarity, converse, symmetric] at localEvidence ⊢
  · exact localEvidence.elim Or.inr Or.inl
  · exact localEvidence.elim Or.inr Or.inl

end VisualProof.Rule
