import VisualProof.Diagram.Concrete.Subgraph.Factorization

namespace VisualProof

namespace RemovalFactorization

private theorem targetWiresFor_length
    {source : ConcreteDiagram sourceDefinitions}
    {target : ConcreteDiagram targetDefinitions}
    (boundary : List source.WireId)
    (targets : Fin boundary.length → target.WireId) :
    (targetWiresFor boundary targets).length = boundary.length := by
  induction boundary with
  | nil => rfl
  | cons _ tail induction =>
      simp only [targetWiresFor, List.length_cons]
      rw [induction (fun position => targets position.succ)]

private theorem targetWiresFor_get
    {source : ConcreteDiagram sourceDefinitions}
    {target : ConcreteDiagram targetDefinitions}
    (boundary : List source.WireId)
    (targets : Fin boundary.length → target.WireId)
    (position : Fin boundary.length) :
    (targetWiresFor boundary targets).get
        ⟨position.val, by
          rw [targetWiresFor_length]
          exact position.isLt⟩ =
      targets position := by
  induction boundary with
  | nil => exact Fin.elim0 position
  | cons head tail induction =>
      refine Fin.cases ?_ (fun tailPosition => ?_) position
      · rfl
      · simpa only [targetWiresFor, List.get_eq_getElem,
          List.getElem_cons_succ] using
          induction (fun position => targets position.succ) tailPosition

/--
One target-independent removal frame carrying two independently checked,
ordered attachment tuples. The origin equations are generated by the concrete
resolver in `Factorization`; callers cannot construct compiler receipts.
-/
structure CommonAttachmentFrame
    {definitions : List (List Sig)}
    {pattern host : CheckedDiagram definitions}
    {occurrence : Occurrence pattern host}
    (removed : RemovalResult occurrence)
    (fragment : CheckedOpenDiagram definitions)
    (source target : ConcreteSpliceAttachment removed fragment) where
  private mk ::
  removal : RemovalCompilation removed
  sourcePositions :
    Vars removal.visible.sigs (checkedBoundarySigs fragment)
  targetPositions :
    Vars removal.visible.sigs (checkedBoundarySigs fragment)
  private source_origins :
    sourcePositions.entries.map
        (fun packed =>
          match packed with
          | ⟨_, value⟩ =>
              ConcreteElaboration.WireContext.origin
                removed.complement.val removal.visible.ids value) =
      targetWiresFor fragment.val.boundary source.target
  private target_origins :
    targetPositions.entries.map
        (fun packed =>
          match packed with
          | ⟨_, value⟩ =>
              ConcreteElaboration.WireContext.origin
                removed.complement.val removal.visible.ids value) =
      targetWiresFor fragment.val.boundary target.target

/--
Generate the shared frame and both ordered attachment views solely from the
checked removal and attachments.
-/
theorem commonAttachmentFrame_complete
    {definitions : List (List Sig)}
    {pattern host : CheckedDiagram definitions}
    {occurrence : Occurrence pattern host}
    {removed : RemovalResult occurrence}
    {fragment : CheckedOpenDiagram definitions}
    (source target : ConcreteSpliceAttachment removed fragment) :
    Nonempty (CommonAttachmentFrame removed fragment source target) := by
  obtain ⟨removal⟩ := removalCompilation_complete removed
  obtain ⟨sourcePositions, sourceOrigins⟩ :=
    removalAttachmentPositions_complete removal source
  obtain ⟨targetPositions, targetOrigins⟩ :=
    removalAttachmentPositions_complete removal target
  exact
    ⟨CommonAttachmentFrame.mk removal sourcePositions targetPositions
      sourceOrigins targetOrigins⟩

namespace CommonAttachmentFrame

def packedOrigin
    (compiled : CommonAttachmentFrame removed fragment source target)
    (packed : PackedVar compiled.removal.visible.sigs) :
    removed.complement.val.WireId :=
  match packed with
  | ⟨_, value⟩ =>
      ConcreteElaboration.WireContext.origin
        removed.complement.val compiled.removal.visible.ids value

def sourcePackedAt
    (compiled : CommonAttachmentFrame removed fragment source target)
    (position : Fin fragment.val.boundary.length) :
    PackedVar compiled.removal.visible.sigs :=
  compiled.sourcePositions.entries.get
    ⟨position.val, by
      rw [ExtractedBoundaryCompiler.entries_length]
      simpa only [checkedBoundarySigs, List.length_map] using
        position.isLt⟩

def targetPackedAt
    (compiled : CommonAttachmentFrame removed fragment source target)
    (position : Fin fragment.val.boundary.length) :
    PackedVar compiled.removal.visible.sigs :=
  compiled.targetPositions.entries.get
    ⟨position.val, by
      rw [ExtractedBoundaryCompiler.entries_length]
      simpa only [checkedBoundarySigs, List.length_map] using
        position.isLt⟩

theorem sourcePackedAt_origin
    (compiled : CommonAttachmentFrame removed fragment source target)
    (position : Fin fragment.val.boundary.length) :
    compiled.packedOrigin (compiled.sourcePackedAt position) =
      source.target position := by
  have atPosition :=
    congrArg (fun values => values[position.val]?) compiled.source_origins
  have entriesBound :
      position.val < compiled.sourcePositions.entries.length := by
    rw [ExtractedBoundaryCompiler.entries_length]
    simpa only [checkedBoundarySigs, List.length_map] using position.isLt
  have leftBound :
      position.val <
        (compiled.sourcePositions.entries.map compiled.packedOrigin).length := by
    simpa only [List.length_map] using entriesBound
  have rightBound :
      position.val <
        (targetWiresFor fragment.val.boundary source.target).length := by
    rw [targetWiresFor_length]
    exact position.isLt
  have exactPosition := Option.some.inj
    ((List.getElem?_eq_getElem leftBound).symm.trans
      (atPosition.trans (List.getElem?_eq_getElem rightBound)))
  have targetAt :=
    targetWiresFor_get fragment.val.boundary source.target position
  simpa only [sourcePackedAt, packedOrigin, List.get_eq_getElem,
    List.getElem_map] using exactPosition.trans targetAt

theorem targetPackedAt_origin
    (compiled : CommonAttachmentFrame removed fragment source target)
    (position : Fin fragment.val.boundary.length) :
    compiled.packedOrigin (compiled.targetPackedAt position) =
      target.target position := by
  have atPosition :=
    congrArg (fun values => values[position.val]?) compiled.target_origins
  have entriesBound :
      position.val < compiled.targetPositions.entries.length := by
    rw [ExtractedBoundaryCompiler.entries_length]
    simpa only [checkedBoundarySigs, List.length_map] using position.isLt
  have leftBound :
      position.val <
        (compiled.targetPositions.entries.map compiled.packedOrigin).length := by
    simpa only [List.length_map] using entriesBound
  have rightBound :
      position.val <
        (targetWiresFor fragment.val.boundary target.target).length := by
    rw [targetWiresFor_length]
    exact position.isLt
  have exactPosition := Option.some.inj
    ((List.getElem?_eq_getElem leftBound).symm.trans
      (atPosition.trans (List.getElem?_eq_getElem rightBound)))
  have targetAt :=
    targetWiresFor_get fragment.val.boundary target.target position
  simpa only [targetPackedAt, packedOrigin, List.get_eq_getElem,
    List.getElem_map] using exactPosition.trans targetAt

end CommonAttachmentFrame

end RemovalFactorization

end VisualProof
