import VisualProof.Diagram.Concrete.Subgraph.Splice.Input.Soundness
import VisualProof.Diagram.Concrete.Subgraph.Splice.AliasMaterialization
import VisualProof.Diagram.Concrete.Subgraph.Splice.AttachmentAliasMaterialization
