export type {
  RegionId, NodeId, WireId, Region, DiagramNode, Port, Endpoint, Wire, Diagram,
} from './diagram'
export { mkDiagram, portKey, requiredPorts, DiagramError } from './diagram'
export { isAncestorOrEqual, cutDepth, polarity } from './regions'
export { DiagramBuilder } from './builder'
export { diagramToJson, diagramFromJson } from './json'
export type { DiagramWithBoundary } from './boundary'
export { mkDiagramWithBoundary, boundaryArity } from './boundary'
export { termShapeKey, positionalPortKey } from './canonical/shape'
export { canonicalForm } from './canonical/canonical'
export { diagramFingerprint, boundaryFingerprint, diagramsIsomorphic } from './canonical/fingerprint'
export type { NodeMatchVerdict } from './canonical/matchkey'
export { closeOverPorts, termsMatchModuloBetaEta } from './canonical/matchkey'
export type { SubgraphSelection, SelectionContents } from './subgraph/selection'
export { mkSelection, selectionContents } from './subgraph/selection'
export type { Extraction } from './subgraph/extract'
export { extractSubgraph } from './subgraph/extract'
export { removeSubgraph, spliceSubgraph } from './subgraph/splice'
export type { Occurrence, UndecidedPair, MatchResult } from './subgraph/match'
export { findOccurrences } from './subgraph/match'
export { occurrenceToSelection } from './subgraph/occurrence'
