import VisualProof.Theory.Definition

namespace VisualProof.Theory

open VisualProof.Diagram

private theorem append_singleton_length (signature : List Nat) (arity : Nat) :
    (signature ++ [arity]).length = signature.length + 1 := by
  simp

theorem namedRel_eq_of_index_eq
    (left right : NamedRel signature arity)
    (index_eq : left.index = right.index) : left = right := by
  cases left
  cases right
  cases index_eq
  rfl

private def extendNamedEnv (prior : NamedEnv D signature)
    (relation : Relation D arity) : NamedEnv D (signature ++ [arity]) :=
  fun requested named => by
    if hlast : named.index.val = signature.length then
      have heq : arity = requested := by
        have hvalue := named.hasArity
        simp only [List.get_eq_getElem] at hvalue
        simpa [hlast] using hvalue
      exact heq ▸ relation
    else
      have hlt : named.index.val < signature.length := by
        have hin := named.index.isLt
        simp only [List.length_append, List.length_cons, List.length_nil] at hin
        omega
      exact prior requested {
        index := ⟨named.index.val, hlt⟩
        hasArity := by
          have hvalue := named.hasArity
          simp only [List.get_eq_getElem] at hvalue ⊢
          simpa [List.getElem_append_left hlt] using hvalue
      }

private theorem extendNamedEnv_agrees_appendRight
    (prior : NamedEnv D signature) (relation : Relation D arity) :
    NamedEnv.Agrees (NamedRenaming.appendRight signature [arity]) prior
      (extendNamedEnv prior relation) := by
  intro requested named args
  have hprior :
      ((NamedRenaming.appendRight signature [arity]).named named).index.val ≠
        signature.length := by
    change named.index.val ≠ signature.length
    exact Nat.ne_of_lt named.index.isLt
  unfold extendNamedEnv
  split
  · rename_i hlast
    exact (hprior hlast).elim
  · apply iff_of_eq
    congr 2

def appendedRelation (definition : Definition signature) :
    NamedRel (signature ++ [definition.arity]) definition.arity where
  index := Fin.cast (append_singleton_length signature definition.arity).symm
    (Fin.last signature.length)
  hasArity := by
    simp [Definition.arity]

/-- The named-relation reference determined by an ordered definition entry. -/
def DefinitionEntry.namedRelation
    (entry : DefinitionEntry signature index) :
    NamedRel signature entry.body.val.boundary.length where
  index := index
  hasArity := entry.body_arity.symm

/-- Structural interpretation of an ordered definition DAG. -/
def interpretDefinitionsIn (model : VisualProof.Lambda.LambdaModel) :
    (definitions : VerifiedDefinitions signature) →
      NamedEnv model.Carrier signature
  | .empty => fun _ relation => Fin.elim0 relation.index
  | .append prior definition =>
      extendNamedEnv (interpretDefinitionsIn model prior)
        (fun args => definition.body.denote model
          (interpretDefinitionsIn model prior) args)

theorem definition_equation_in (model : VisualProof.Lambda.LambdaModel)
    (prior : VerifiedDefinitions signature)
    (definition : Definition signature)
    (args : Fin definition.arity → model.Carrier) :
    (interpretDefinitionsIn model (.append prior definition))
      definition.arity (appendedRelation definition) args ↔
      definition.body.denote model (interpretDefinitionsIn model prior) args := by
  simp [interpretDefinitionsIn, extendNamedEnv, appendedRelation]

/-- Every entry of an ordered definition DAG satisfies its defining equation
in the environment generated by the complete DAG. -/
theorem interpretDefinitions_entry_equation_in
    (model : VisualProof.Lambda.LambdaModel) :
    ∀ (definitions : VerifiedDefinitions signature)
      (index : Fin signature.length)
      (args : Fin (definitions.entry index).body.val.boundary.length →
        model.Carrier),
      (interpretDefinitionsIn model definitions)
          (definitions.entry index).body.val.boundary.length
          (definitions.entry index).namedRelation args ↔
        (definitions.entry index).body.denote model
          (interpretDefinitionsIn model definitions) args := by
  intro definitions
  induction definitions with
  | empty => intro index; exact Fin.elim0 index
  | @append priorSignature prior definition ih =>
      intro index
      by_cases hprior : index.val < priorSignature.length
      · let priorIndex : Fin priorSignature.length := ⟨index.val, hprior⟩
        let priorEntry := prior.entry priorIndex
        have entry_eq :
            (VerifiedDefinitions.append prior definition).entry index = {
              body := priorEntry.body.weakenRight [definition.arity]
              body_arity := by
                simpa [priorEntry, priorIndex, List.get_eq_getElem,
                  List.getElem_append_left hprior] using priorEntry.body_arity
            } := by
          simp [VerifiedDefinitions.entry, hprior, priorIndex, priorEntry]
        rw [entry_eq]
        intro args
        have agrees := extendNamedEnv_agrees_appendRight
          (interpretDefinitionsIn model prior)
          (fun values => definition.body.denote model
            (interpretDefinitionsIn model prior) values)
        have named_eq :
            ({
              body := priorEntry.body.weakenRight [definition.arity]
              body_arity := by
                simpa [priorEntry, priorIndex, List.get_eq_getElem,
                  List.getElem_append_left hprior] using priorEntry.body_arity
            } : DefinitionEntry (priorSignature ++ [definition.arity]) index).namedRelation =
              (NamedRenaming.appendRight priorSignature [definition.arity]).named
                priorEntry.namedRelation := by
          apply namedRel_eq_of_index_eq
          apply Fin.ext
          rfl
        rw [named_eq]
        change
          (extendNamedEnv (interpretDefinitionsIn model prior)
              (fun values => definition.body.denote model
                (interpretDefinitionsIn model prior) values))
              priorEntry.body.val.boundary.length
              ((NamedRenaming.appendRight priorSignature
                [definition.arity]).named priorEntry.namedRelation) args ↔ _
        constructor
        · intro hresult
          have hpriorResult := (agrees priorEntry.body.val.boundary.length
            priorEntry.namedRelation args).mp hresult
          have hbody := (ih priorIndex args).mp hpriorResult
          exact (priorEntry.body.weakenRight_denote [definition.arity] model
            (interpretDefinitionsIn model prior)
            (interpretDefinitionsIn model (.append prior definition)) agrees args).mpr
              hbody
        · intro hbody
          have hpriorBody := (priorEntry.body.weakenRight_denote
            [definition.arity] model (interpretDefinitionsIn model prior)
            (interpretDefinitionsIn model (.append prior definition)) agrees args).mp
              hbody
          have hpriorResult := (ih priorIndex args).mpr hpriorBody
          exact (agrees priorEntry.body.val.boundary.length
            priorEntry.namedRelation args).mpr hpriorResult
      · have hlast : index.val = priorSignature.length := by
          have hin := index.isLt
          simp only [List.length_append, List.length_cons, List.length_nil] at hin
          omega
        have entry_eq :
            (VerifiedDefinitions.append prior definition).entry index = {
              body := definition.body.weakenRight [definition.arity]
              body_arity := by
                simp [Definition.arity, hlast, List.get_eq_getElem]
            } := by
          simp [VerifiedDefinitions.entry, hlast]
        rw [entry_eq]
        intro args
        have named_eq :
            ({
              body := definition.body.weakenRight [definition.arity]
              body_arity := by
                simp [Definition.arity, hlast, List.get_eq_getElem]
            } : DefinitionEntry (priorSignature ++ [definition.arity]) index).namedRelation =
              appendedRelation definition := by
          apply namedRel_eq_of_index_eq
          apply Fin.ext
          exact hlast
        rw [named_eq]
        change
          (interpretDefinitionsIn model (.append prior definition))
              definition.arity (appendedRelation definition) args ↔
            (definition.body.weakenRight [definition.arity]).denote model
              (interpretDefinitionsIn model (.append prior definition)) args
        rw [definition_equation_in]
        exact (definition.body.weakenRight_denote [definition.arity] model
          (interpretDefinitionsIn model prior)
          (interpretDefinitionsIn model (.append prior definition))
          (extendNamedEnv_agrees_appendRight _ _) args).symm

/-- The sole public interpretation of an ordered definition DAG for system
validity: closed lambda individuals modulo beta-eta equivalence. -/
noncomputable def interpretDefinitions
    (definitions : VerifiedDefinitions signature) :
    NamedEnv VisualProof.Lambda.Individual signature :=
  interpretDefinitionsIn VisualProof.Lambda.canonicalModel definitions

theorem definition_equation
    (prior : VerifiedDefinitions signature)
    (definition : Definition signature)
    (args : Fin definition.arity → VisualProof.Lambda.Individual) :
    (interpretDefinitions (.append prior definition))
        definition.arity (appendedRelation definition) args ↔
      definition.body.denote VisualProof.Lambda.canonicalModel
        (interpretDefinitions prior) args :=
  definition_equation_in VisualProof.Lambda.canonicalModel prior definition args

theorem interpretDefinitions_entry_equation
    (definitions : VerifiedDefinitions signature)
    (index : Fin signature.length)
    (args : Fin (definitions.entry index).body.val.boundary.length →
      VisualProof.Lambda.Individual) :
    (interpretDefinitions definitions)
        (definitions.entry index).body.val.boundary.length
        (definitions.entry index).namedRelation args ↔
      (definitions.entry index).body.denote
        VisualProof.Lambda.canonicalModel (interpretDefinitions definitions) args :=
  interpretDefinitions_entry_equation_in VisualProof.Lambda.canonicalModel
    definitions index args

end VisualProof.Theory
