import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import type { Theory } from '../src/kernel/proof/store'
import { theoryToJson } from '../src/kernel/proof/store'
import { buildFregeTheory } from '../src/theories/frege'
import { buildLambdaTheory } from '../src/theories/lambda'

/**
 * Emit the example theories as ORDINARY files in a repo-root `examples/`
 * directory. Each generator is the tested source of truth; theoryToJson
 * serializes it with stable key order. These files carry NO privilege: the app
 * has no built-in knowledge of them and never fetches them — a user opens the
 * `examples/` folder through the same picker as any other folder. The directory
 * is git-ignored and regenerated by the pre-serve/pre-build hooks, so it is
 * always fresh without being a manifest or a shipped-content category.
 */
const here = dirname(fileURLToPath(import.meta.url))
const defaultOutDir = join(here, '..', 'examples')

const sources: readonly { readonly file: string; readonly build: () => Theory }[] = [
  { file: 'frege.json', build: buildFregeTheory },
  { file: 'lambda.json', build: buildLambdaTheory },
]

/** Write every example theory file into `outDir`, creating it if needed. Returns
 *  the file names written. No manifest is produced and nothing is deleted. */
export function emitTheories(outDir: string): { written: string[] } {
  mkdirSync(outDir, { recursive: true })
  const written: string[] = []
  for (const { file, build } of sources) {
    writeFileSync(join(outDir, file), `${JSON.stringify(theoryToJson(build()))}\n`)
    written.push(file)
  }
  return { written }
}

const isMain = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href
if (isMain) {
  const { written } = emitTheories(defaultOutDir)
  console.log(`emitted ${written.length} example theories to ${defaultOutDir}`)
}
