import VisualProof.Proof.Theorem

namespace VisualProof.Proof

open VisualProof
open Rule

/-- Ordered theorem verification over one already ordered definition DAG.
Each theorem is checked against exactly the preceding theorem prefix, so no
forward or cyclic citation can be represented. -/
inductive VerifiedTheorems
    (definitions : Theory.VerifiedDefinitions signature) :
    List (TheoremSchema signature) → Type
  | empty : VerifiedTheorems definitions []
  | append {prior : List (TheoremSchema signature)}
      (verified : VerifiedTheorems definitions prior)
      (checked : CheckedTheorem {
        definitions := definitions
        theorems := prior
      }) :
      VerifiedTheorems definitions (prior ++ [checked.schema])

namespace VerifiedTheorems

/-- The context generated by an ordered theorem chain. -/
def context (definitions : Theory.VerifiedDefinitions signature)
    {theorems : List (TheoremSchema signature)}
    (_ : VerifiedTheorems definitions theorems) : ProofContext signature := {
  definitions := definitions
  theorems := theorems
}

/-- Every theorem in an ordered checked prefix is semantically valid. -/
theorem context_valid
    {theorems : List (TheoremSchema signature)}
    (verified : VerifiedTheorems definitions theorems) :
    (verified.context definitions).Valid := by
  induction verified with
  | empty =>
      exact ⟨fun index => Fin.elim0 index⟩
  | append prior checked ih =>
      exact checked.register_valid ih

end VerifiedTheorems

/-- A complete verified logical theory: ordered definitions together with an
ordered theorem chain checked against those definitions and earlier theorems. -/
structure VerifiedTheory (signature : List Nat) where
  definitions : Theory.VerifiedDefinitions signature
  theorems : List (TheoremSchema signature)
  verification : VerifiedTheorems definitions theorems

namespace VerifiedTheory

def context (theory : VerifiedTheory signature) : ProofContext signature := {
  definitions := theory.definitions
  theorems := theory.theorems
}

/-- Ordered-theory soundness: all registered citations denote valid open
implications in the structurally interpreted definition environment. -/
theorem sound (theory : VerifiedTheory signature)
    : theory.context.Valid := by
  exact theory.verification.context_valid

theorem theorem_sound (theory : VerifiedTheory signature)
    (index : Fin theory.theorems.length) :
    (theory.theorems.get index).Valid
      (Theory.interpretDefinitions theory.definitions) :=
  theory.sound.theorems index

end VerifiedTheory

/-- Public formulation matching theory verification: membership in the
verified context entails semantic validity, including citations of any earlier
registered theorem. -/
theorem verifiedTheory_sound
    (theory : VerifiedTheory signature)
    (schema : TheoremSchema signature) (member : schema ∈ theory.theorems) :
    schema.Valid (Theory.interpretDefinitions theory.definitions) := by
  obtain ⟨index, hget⟩ := List.mem_iff_get.mp member
  rw [← hget]
  exact theory.theorem_sound index

end VisualProof.Proof
