import VisualProof.Proof.Theorem

namespace VisualProof.Proof

open VisualProof
open Rule

/-- Ordered theorem verification. Each theorem is checked against exactly the
preceding theorem prefix, so no forward or cyclic citation can be represented. -/
inductive VerifiedTheorems : List (TheoremSchema ) → Type
  | empty : VerifiedTheorems []
  | append {prior : List (TheoremSchema )}
      (verified : VerifiedTheorems prior)
      (checked : CheckedTheorem {
        theorems := prior
      }) :
      VerifiedTheorems (prior ++ [checked.schema])

namespace VerifiedTheorems

/-- The context generated by an ordered theorem chain. -/
def context {theorems : List (TheoremSchema )}
    (_ : VerifiedTheorems theorems) : ProofContext  := {
  theorems := theorems
}

/-- Every theorem in an ordered checked prefix is semantically valid. -/
theorem context_valid
    {theorems : List (TheoremSchema )}
    (verified : VerifiedTheorems theorems) :
    verified.context.Valid model := by
  induction verified with
  | empty =>
      exact ⟨fun index => Fin.elim0 index⟩
  | append prior checked ih =>
      exact checked.register_valid ih

end VerifiedTheorems

/-- A complete verified logical theory: an ordered theorem chain checked
against its earlier theorem prefixes. -/
structure VerifiedTheory where
  theorems : List (TheoremSchema )
  verification : VerifiedTheorems theorems

namespace VerifiedTheory

def context (theory : VerifiedTheory ) : ProofContext  := {
  theorems := theory.theorems
}

/-- Ordered-theory soundness: all registered citations denote valid open
implications. -/
theorem sound (theory : VerifiedTheory )
    (model : Model) : theory.context.Valid model := by
  exact theory.verification.context_valid

theorem theorem_sound (theory : VerifiedTheory )
    (model : Model)
    (index : Fin theory.theorems.length) :
    (theory.theorems.get index).Valid
      model :=
  (theory.sound model).theorems index

end VerifiedTheory

/-- Public formulation matching theory verification: membership in the
verified context entails semantic validity, including citations of any earlier
registered theorem. -/
theorem verifiedTheory_sound
    (theory : VerifiedTheory )
    (model : Model)
    (schema : TheoremSchema ) (member : schema ∈ theory.theorems) :
    schema.Valid model := by
  obtain ⟨index, hget⟩ := List.mem_iff_get.mp member
  rw [← hget]
  exact theory.theorem_sound model index

end VisualProof.Proof
