import VisualProof.Concrete.Subgraph.Splice.Input.Soundness
import VisualProof.Concrete.Subgraph.Splice.AliasMaterialization
import VisualProof.Concrete.Subgraph.Splice.AttachmentAliasMaterialization
