import { DiagramBuilder } from '../src/kernel/diagram/builder'
import { relSig, TERM } from '../src/kernel/diagram/sig'
import type { WireId } from '../src/kernel/diagram/diagram'
import { mkEngine } from '../src/view/engine'
import type { WireView, WireLeg, WireLegEnd } from '../src/view/engine'
import { settleStep, totalEnergy, recomputeRegions, establishFrame } from '../src/view/relax'
import { mkLegCache } from '../src/view/elastica'
const rel = (n: number) => relSig(Array.from({ length: n }, () => TERM))
function fourWay() { const b = new DiagramBuilder(); const r1 = b.ref(b.root, 'a', rel(3)); const r2 = b.ref(b.root, 'bb', rel(3)); const r3 = b.ref(b.root, 'cc', rel(3)); const r4 = b.ref(b.root, 'dd', rel(3)); b.wire(b.root, [{ node: r1, port: { kind: 'arg', index: 0 } }, { node: r2, port: { kind: 'arg', index: 0 } }, { node: r3, port: { kind: 'arg', index: 0 } }, { node: r4, port: { kind: 'arg', index: 0 } }]); return b.build() }
function setPairing(w: WireView, i: number, j: number, k: number, l: number, c: readonly { x: number; y: number }[], coincident = false) { const bind = (n: number): WireLegEnd => ({ kind: 'bind', i: n }); const br = (n: number): WireLegEnd => ({ kind: 'branch', i: n }); const mid = (a: any, b: any) => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }); const centre = { x: (c[i]!.x + c[j]!.x + c[k]!.x + c[l]!.x) / 4, y: (c[i]!.y + c[j]!.y + c[k]!.y + c[l]!.y) / 4 }; const B0 = coincident ? { ...centre } : mid(c[i]!, c[j]!); const B1 = coincident ? { ...centre } : mid(c[k]!, c[l]!); const chord = (f: any, t: any) => Math.atan2(t.y - f.y, t.x - f.x); const mk = (a: WireLegEnd, b: WireLegEnd, f: any, t: any): WireLeg => ({ a, b, angA: chord(f, t), angB: chord(f, t), cache: mkLegCache() }); w.branches.length = 0; w.branches.push(B0, B1); w.legs.length = 0; for (const lg of [mk(bind(i), br(0), c[i]!, B0), mk(bind(j), br(0), c[j]!, B0), mk(bind(k), br(1), c[k]!, B1), mk(bind(l), br(1), c[l]!, B1), mk(br(0), br(1), B0, B1)]) w.legs.push(lg) }
function pairing(w: WireView) { const per = new Map<number, number[]>(); for (const leg of w.legs) { let br = -1, term = -1; for (const end of [leg.a, leg.b]) { if (end.kind === 'branch') br = end.i; if (end.kind === 'bind') term = end.i } if (br >= 0 && term >= 0) { const a = per.get(br) ?? []; a.push(term); per.set(br, a) } } return [...per.values()].map(a => a.sort().join('')).sort().join('|') }
const gap = (w: WireView) => Math.hypot(w.branches[0]!.x - w.branches[1]!.x, w.branches[0]!.y - w.branches[1]!.y)
const INTERLEAVED = [{ x: -30, y: 0 }, { x: 30, y: 0 }, { x: -6, y: 0 }, { x: 6, y: 0 }]
function pin(corners: any[], pair: [number, number, number, number], coincident = false) { const e = mkEngine(fourWay(), [] as readonly WireId[]); const w = [...e.wires.values()].find(x => x.binds.length === 4)!; const cx = (corners[0].x + corners[1].x + corners[2].x + corners[3].x) / 4, cy = (corners[0].y + corners[1].y + corners[2].y + corners[3].y) / 4; const pinned = new Set<string>(); w.binds.forEach((bd, n) => { const b = e.bodies.get(bd.body)!; b.pos = { ...corners[n] }; const la = b.localAnchor.get(bd.key)!; b.theta = Math.atan2(cy - b.pos.y, cx - b.pos.x) - Math.atan2(la.y, la.x); pinned.add(bd.body) }); setPairing(w, pair[0], pair[1], pair[2], pair[3], corners, coincident); recomputeRegions(e); establishFrame(e); return { e, w, pinned } }
console.log('=== ACCEPT: 01|23 interleaved ===')
{ const { e, w, pinned } = pin(INTERLEAVED, [0, 1, 2, 3]); console.log('start', pairing(w), 'gap', gap(w).toFixed(6), 'E', totalEnergy(e).toFixed(3), 'scale', e.scale, 'b0', w.branches[0], 'b1', w.branches[1]); for (let t = 0; t < 30; t++) { const p0 = pairing(w); const moved = settleStep(e, pinned); console.log(`t${t} pair=${pairing(w)} gap=${gap(w).toFixed(4)} E=${totalEnergy(e).toFixed(3)} moved=${moved}${pairing(w) !== p0 ? ' <<CROSS' : ''}`); if (!moved) break } }
console.log('=== REFUSE: 02|13 coincident ===')
{ const { e, w, pinned } = pin(INTERLEAVED, [0, 2, 1, 3], true); console.log('start', pairing(w), 'gap', gap(w).toFixed(6)); for (let t = 0; t < 30; t++) { const p0 = pairing(w); const moved = settleStep(e, pinned); console.log(`t${t} pair=${pairing(w)} gap=${gap(w).toFixed(4)} E=${totalEnergy(e).toFixed(3)} moved=${moved}${pairing(w) !== p0 ? ' <<CROSS' : ''}`); if (!moved) break } }
console.log('=== ACCEPT long run (800) ===')
{ const { e, w, pinned } = pin(INTERLEAVED, [0, 1, 2, 3]); let cross=0; let lastp=pairing(w); for (let t = 0; t < 800; t++) { const p0=pairing(w); const moved = settleStep(e, pinned); if(pairing(w)!==p0){cross++; if(t<60||cross<8)console.log(`  t${t} ${p0}->${pairing(w)} gap=${gap(w).toFixed(4)} E=${totalEnergy(e).toFixed(2)}`)} if (!moved){console.log('  STOP t'+t);break} } console.log('final', pairing(w), 'gap', gap(w).toFixed(4), 'E', totalEnergy(e).toFixed(2), 'crosses', cross) }
