import { DiagramBuilder } from '../src/kernel/diagram/builder'
import { relSig, TERM } from '../src/kernel/diagram/sig'
import type { WireId } from '../src/kernel/diagram/diagram'
import { mkEngine, resolveLeg, traceLeg } from '../src/view/engine'
import type { WireView, WireLeg, WireLegEnd } from '../src/view/engine'
import { settleStep, totalEnergy, recomputeRegions, establishFrame } from '../src/view/relax'
import { QN, mkLegCache } from '../src/view/elastica'
const rel = (n: number) => relSig(Array.from({ length: n }, () => TERM))
function fourWay() { const b = new DiagramBuilder(); const r1 = b.ref(b.root, 'a', rel(3)); const r2 = b.ref(b.root, 'bb', rel(3)); const r3 = b.ref(b.root, 'cc', rel(3)); const r4 = b.ref(b.root, 'dd', rel(3)); b.wire(b.root, [{ node: r1, port: { kind: 'arg', index: 0 } }, { node: r2, port: { kind: 'arg', index: 0 } }, { node: r3, port: { kind: 'arg', index: 0 } }, { node: r4, port: { kind: 'arg', index: 0 } }]); return b.build() }
function setPairing(w: WireView, i: number, j: number, k: number, l: number, c: readonly { x: number; y: number }[], coincident = false) { const bind = (n: number): WireLegEnd => ({ kind: 'bind', i: n }); const br = (n: number): WireLegEnd => ({ kind: 'branch', i: n }); const mid = (a: any, b: any) => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }); const centre = { x: (c[i]!.x + c[j]!.x + c[k]!.x + c[l]!.x) / 4, y: (c[i]!.y + c[j]!.y + c[k]!.y + c[l]!.y) / 4 }; const B0 = coincident ? { ...centre } : mid(c[i]!, c[j]!); const B1 = coincident ? { ...centre } : mid(c[k]!, c[l]!); const chord = (f: any, t: any) => Math.atan2(t.y - f.y, t.x - f.x); const mk = (a: WireLegEnd, b: WireLegEnd, f: any, t: any): WireLeg => ({ a, b, angA: chord(f, t), angB: chord(f, t), cache: mkLegCache() }); w.branches.length = 0; w.branches.push(B0, B1); w.legs.length = 0; for (const lg of [mk(bind(i), br(0), c[i]!, B0), mk(bind(j), br(0), c[j]!, B0), mk(bind(k), br(1), c[k]!, B1), mk(bind(l), br(1), c[l]!, B1), mk(br(0), br(1), B0, B1)]) w.legs.push(lg) }
function pairing(w: WireView) { const per = new Map<number, number[]>(); for (const leg of w.legs) { let br = -1, term = -1; for (const end of [leg.a, leg.b]) { if (end.kind === 'branch') br = end.i; if (end.kind === 'bind') term = end.i } if (br >= 0 && term >= 0) { const a = per.get(br) ?? []; a.push(term); per.set(br, a) } } return [...per.values()].map(a => a.sort().join('')).sort().join('|') }
const gap = (w: WireView) => Math.hypot(w.branches[0]!.x - w.branches[1]!.x, w.branches[0]!.y - w.branches[1]!.y)
function cloud(e:any,w:WireView){const pts:any[]=[];for(const leg of w.legs){const s=resolveLeg(e,w,leg);const o:any[]=[];traceLeg(s,o,QN);for(const p of o)pts.push(p)}return pts.sort((a,b)=>a.x-b.x||a.y-b.y)}
function haus(a:any[],b:any[]){let w=0;for(const p of a){let best=Infinity;for(const q of b){const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<best)best=d}w=Math.max(w,best)}return w}
function pin(corners: any[], pair: [number, number, number, number], coincident = false) { const e = mkEngine(fourWay(), [] as readonly WireId[]); const w = [...e.wires.values()].find(x => x.binds.length === 4)!; const cx = (corners[0].x + corners[1].x + corners[2].x + corners[3].x) / 4, cy = (corners[0].y + corners[1].y + corners[2].y + corners[3].y) / 4; const pinned = new Set<string>(); w.binds.forEach((bd, n) => { const b = e.bodies.get(bd.body)!; b.pos = { ...corners[n] }; const la = b.localAnchor.get(bd.key)!; b.theta = Math.atan2(cy - b.pos.y, cx - b.pos.x) - Math.atan2(la.y, la.x); pinned.add(bd.body) }); setPairing(w, pair[0], pair[1], pair[2], pair[3], corners, coincident); recomputeRegions(e); establishFrame(e); return { e, w, pinned } }
const WIDE = [{ x: -40, y: -12 }, { x: -40, y: 12 }, { x: 40, y: -12 }, { x: 40, y: 12 }]
// CONTINUITY: crossing sweep drawing identical
{ const { e, w, pinned } = pin(WIDE, [0, 1, 2, 3], true); let checked=false; for (let t = 0; t < 400; t++) { const p0 = pairing(w); const before=cloud(e,w); settleStep(e, pinned); if(pairing(w)!==p0){const after=cloud(e,w);const d=Math.max(haus(before,after),haus(after,before));console.log(`CROSS at t${t}: ${p0}->${pairing(w)} haus=${d.toFixed(4)}`);checked=true;break} } if(!checked)console.log('no cross for continuity') }
// DETERMINISM
function snap(){const{e,w,pinned}=pin(WIDE,[0,1,2,3],true);for(let t=0;t<200;t++)if(!settleStep(e,pinned))break;const o:number[]=[];for(const b of e.bodies.values())o.push(b.pos.x,b.pos.y,b.theta);for(const lg of w.legs)o.push(lg.angA,lg.angB);for(const bp of w.branches)o.push(bp.x,bp.y);o.push(pairing(w).length);return o}
{const a=snap(),b=snap();let md=0;if(a.length!==b.length)console.log('LEN MISMATCH',a.length,b.length);else{for(let i=0;i<a.length;i++)md=Math.max(md,Math.abs(a[i]!-b[i]!));console.log('determinism maxd=',md,'finalPair=',pairing(pin(WIDE,[0,1,2,3],true).w))}}
