import { DiagramBuilder } from '../src/kernel/diagram/builder'
import { relSig, TERM } from '../src/kernel/diagram/sig'
import type { WireId } from '../src/kernel/diagram/diagram'
import { mkEngine } from '../src/view/engine'
import type { WireView, WireLeg, WireLegEnd } from '../src/view/engine'
import { settleStep, totalEnergy, recomputeRegions, establishFrame } from '../src/view/relax'
import { mkLegCache } from '../src/view/elastica'
const rel = (n: number) => relSig(Array.from({ length: n }, () => TERM))
function fourWay() { const b = new DiagramBuilder(); const r1 = b.ref(b.root, 'a', rel(3)); const r2 = b.ref(b.root, 'bb', rel(3)); const r3 = b.ref(b.root, 'cc', rel(3)); const r4 = b.ref(b.root, 'dd', rel(3)); b.wire(b.root, [{ node: r1, port: { kind: 'arg', index: 0 } }, { node: r2, port: { kind: 'arg', index: 0 } }, { node: r3, port: { kind: 'arg', index: 0 } }, { node: r4, port: { kind: 'arg', index: 0 } }]); return b.build() }
const WIDE = [{ x: -40, y: -12 }, { x: -40, y: 12 }, { x: 40, y: -12 }, { x: 40, y: 12 }]
function setPairing(w: WireView, i: number, j: number, k: number, l: number, c: any[], b0: any, b1: any) { const bind = (n: number): WireLegEnd => ({ kind: 'bind', i: n }); const br = (n: number): WireLegEnd => ({ kind: 'branch', i: n }); const chord = (f: any, t: any) => Math.atan2(t.y - f.y, t.x - f.x); const mk = (a: WireLegEnd, bb: WireLegEnd, f: any, t: any): WireLeg => ({ a, b: bb, angA: chord(f, t), angB: chord(f, t), cache: mkLegCache() }); w.branches.length = 0; w.branches.push({...b0},{...b1}); w.legs.length = 0; for (const lg of [mk(bind(i), br(0), c[i], b0), mk(bind(j), br(0), c[j], b0), mk(bind(k), br(1), c[k], b1), mk(bind(l), br(1), c[l], b1), mk(br(0), br(1), b0, b1)]) w.legs.push(lg) }
function pairing(w: WireView) { const per = new Map<number, number[]>(); for (const leg of w.legs) { let br = -1, term = -1; for (const end of [leg.a, leg.b]) { if (end.kind === 'branch') br = end.i; if (end.kind === 'bind') term = end.i } if (br >= 0 && term >= 0) { const a = per.get(br) ?? []; a.push(term); per.set(br, a) } } return [...per.values()].map(a => a.sort().join('')).sort().join('|') }
function pin(pair: [number,number,number,number], b0:any, b1:any) { const e = mkEngine(fourWay(), [] as readonly WireId[]); const w = [...e.wires.values()].find(x => x.binds.length === 4)!; const pinned = new Set<string>(); w.binds.forEach((bd, n) => { const b = e.bodies.get(bd.body)!; b.pos = { ...WIDE[n]! }; const la = b.localAnchor.get(bd.key)!; b.theta = Math.atan2(-b.pos.y, -b.pos.x) - Math.atan2(la.y, la.x); pinned.add(bd.body) }); setPairing(w, pair[0], pair[1], pair[2], pair[3], WIDE, b0, b1); recomputeRegions(e); establishFrame(e); return { e, w, pinned } }
function checkMono(label:string, pair:[number,number,number,number], b0:any, b1:any){const{e,w,pinned}=pin(pair,b0,b1);let prev=totalEnergy(e);let worstRise=0,riseSweep=-1;const crosses:string[]=[];for(let t=0;t<800;t++){const p0=pairing(w);const m=settleStep(e,pinned);const cur=totalEnergy(e);const rise=cur-prev;if(rise>worstRise){worstRise=rise;riseSweep=t}if(pairing(w)!==p0)crosses.push(`t${t}:${p0}->${pairing(w)}(dE=${rise.toFixed(3)})`);prev=cur;if(!m)break}console.log(`${label}: final=${pairing(w)} worstRise=${worstRise.toExponential(3)}@t${riseSweep} crosses=[${crosses.join(', ')}]`)}
checkMono('ACCEPT 01|23@face', [0,1,2,3], {x:-0.003,y:0},{x:0.003,y:0})
checkMono('REFUSE 02|13@face-vert', [0,2,1,3], {x:0,y:-0.003},{x:0,y:0.003})
checkMono('02|13@face-horiz', [0,2,1,3], {x:-0.003,y:0},{x:0.003,y:0})
checkMono('03|12@face', [0,3,1,2], {x:-0.003,y:0},{x:0.003,y:0})
